module Aladdin.Front.Analyzer.Parser where

import Aladdin.Front.Analyzer.Grammar
import Aladdin.Front.Header
import qualified Control.Monad.Trans.Class as Y
import qualified Control.Monad.Trans.Except as Y
import qualified Control.Monad.Trans.State.Strict as Y
import qualified Data.Map.Strict as YMap
import qualified Data.Set as YSet

type ParserS = Int

type NSym = Int

type TSym = Int

data Sym
    = NS NSym
    | TS TSym
    deriving (Eq, Ord)

data Action
    = Shift ParserS
    | Reduce (NSym, [Sym])
    | Accept
    deriving (Eq)

data LR1Parser
    = LR1Parser
        { getInitialS :: ParserS
        , getActionTable :: YMap.Map (ParserS, TSym) Action
        , getReduceTable :: YMap.Map (ParserS, NSym) ParserS
        }
    deriving ()

data ParsingTree
    = PTLeaf (Token)
    | PTBranch NSym [ParsingTree]
    deriving ()


-- the following codes are generated by PGS.

runAladdinParser :: [Token] -> Either (Maybe (Token)) (Either TermRep [DeclRep])
runAladdinParser = fmap (getEither getQuery (getSequence getDecl)) . runLR1 theLR1Parser where
    getQuery :: ParsingTree -> (TermRep)
    getQuery (PTBranch _ [PTLeaf (T_quest loc_1), _2@(PTBranch guard2 _), PTLeaf (T_dot loc_3)])
        | [guard2] `elem` [[3]] =
            (getTermRep0 _2)
    getDecl :: ParsingTree -> (DeclRep)
    getDecl (PTBranch _ [PTLeaf (T_kind loc_1), PTLeaf (T_smallid loc_2 contents_2), _3@(PTBranch guard3 _), PTLeaf (T_dot loc_4)])
        | [guard3] `elem` [[14]] =
            RKindDecl ((loc_1) <> (loc_4)) (TC_Named (contents_2)) (getKindRep0 _3)
    getDecl (PTBranch _ [PTLeaf (T_type loc_1), PTLeaf (T_smallid loc_2 contents_2), _3@(PTBranch guard3 _), PTLeaf (T_dot loc_4)])
        | [guard3] `elem` [[16]] =
            RTypeDecl ((loc_1) <> (loc_4)) (DC_Named (contents_2)) (getTypeRep0 _3)
    getDecl (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_dot loc_2)])
        | [guard1] `elem` [[3]] =
            RFactDecl (getSLoc (getTermRep0 _1) <> (loc_2)) (getTermRep0 _1)
    getKindRep0 :: ParsingTree -> (KindRep)
    getKindRep0 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_arrow loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[15, 14]] =
            RKArr (getSLoc (getKindRep1 _1) <> getSLoc (getKindRep0 _3)) (getKindRep1 _1) (getKindRep0 _3)
    getKindRep0 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[15]] =
            (getKindRep1 _1)
    getKindRep1 :: ParsingTree -> (KindRep)
    getKindRep1 (PTBranch _ [PTLeaf (T_type loc_1)])
        | otherwise =
            RStar (loc_1)
    getKindRep1 (PTBranch _ [PTLeaf (T_lparen loc_1), _2@(PTBranch guard2 _), PTLeaf (T_rparen loc_3)])
        | [guard2] `elem` [[14]] =
            RKPrn ((loc_1) <> (loc_3)) (getKindRep0 _2)
    getTypeRep0 :: ParsingTree -> (TypeRep)
    getTypeRep0 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_arrow loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[17, 16]] =
            RTyApp (getSLoc (getTypeRep1 _1) <> getSLoc (getTypeRep0 _3)) (RTyApp (getSLoc (getTypeRep1 _1) <> (loc_2)) (RTyCon (loc_2) TC_Arrow) (getTypeRep1 _1)) (getTypeRep0 _3)
    getTypeRep0 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[17]] =
            (getTypeRep1 _1)
    getTypeRep1 :: ParsingTree -> (TypeRep)
    getTypeRep1 (PTBranch _ [_1@(PTBranch guard1 _), _2@(PTBranch guard2 _)])
        | [guard1, guard2] `elem` [[17, 18]] =
            RTyApp (getSLoc (getTypeRep1 _1) <> getSLoc (getTypeRep2 _2)) (getTypeRep1 _1) (getTypeRep2 _2)
    getTypeRep1 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[18]] =
            (getTypeRep2 _1)
    getTypeRep2 :: ParsingTree -> (TypeRep)
    getTypeRep2 (PTBranch _ [PTLeaf (T_largeid loc_1 contents_1)])
        | otherwise =
            RTyVar (loc_1) (contents_1)
    getTypeRep2 (PTBranch _ [PTLeaf (T_smallid loc_1 contents_1)])
        | otherwise =
            RTyCon (loc_1) (TC_Named (contents_1))
    getTypeRep2 (PTBranch _ [PTLeaf (T_lparen loc_1), _2@(PTBranch guard2 _), PTLeaf (T_rparen loc_3)])
        | [guard2] `elem` [[16]] =
            RTyPrn ((loc_1) <> (loc_3)) (getTypeRep0 _2)
    getTermRep0 :: ParsingTree -> (TermRep)
    getTermRep0 (PTBranch _ [PTLeaf (T_largeid loc_1 contents_1), PTLeaf (T_bslash loc_2), _3@(PTBranch guard3 _)])
        | [guard3] `elem` [[3]] =
            RAbs ((loc_1) <> getSLoc (getTermRep0 _3)) (contents_1) (getTermRep0 _3)
    getTermRep0 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_if loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[4, 3]] =
            RApp (getSLoc (getTermRep1 _1) <> getSLoc (getTermRep0 _3)) (RApp (getSLoc (getTermRep1 _1) <> (loc_2)) (RCon (loc_2) (DC_LO LO_if)) (getTermRep1 _1)) (getTermRep0 _3)
    getTermRep0 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[4]] =
            (getTermRep1 _1)
    getTermRep1 :: ParsingTree -> (TermRep)
    getTermRep1 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_semicolon loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[4, 5]] =
            RApp (getSLoc (getTermRep1 _1) <> getSLoc (getTermRep2 _3)) (RApp (getSLoc (getTermRep1 _1) <> (loc_2)) (RCon (loc_2) (DC_LO LO_or)) (getTermRep1 _1)) (getTermRep2 _3)
    getTermRep1 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[5]] =
            (getTermRep2 _1)
    getTermRep2 :: ParsingTree -> (TermRep)
    getTermRep2 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_fatarrow loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[6, 5]] =
            RApp (getSLoc (getTermRep3 _1) <> getSLoc (getTermRep2 _3)) (RApp (getSLoc (getTermRep3 _1) <> (loc_2)) (RCon (loc_2) (DC_LO LO_imply)) (getTermRep3 _1)) (getTermRep2 _3)
    getTermRep2 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[6]] =
            (getTermRep3 _1)
    getTermRep3 :: ParsingTree -> (TermRep)
    getTermRep3 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_comma loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[6, 7]] =
            RApp (getSLoc (getTermRep3 _1) <> getSLoc (getTermRep4 _3)) (RApp (getSLoc (getTermRep3 _1) <> (loc_2)) (RCon (loc_2) (DC_LO LO_and)) (getTermRep3 _1)) (getTermRep4 _3)
    getTermRep3 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[7]] =
            (getTermRep4 _1)
    getTermRep4 :: ParsingTree -> (TermRep)
    getTermRep4 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_cons loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[8, 7]] =
            RApp (getSLoc (getTermRep5 _1) <> getSLoc (getTermRep4 _3)) (RApp (getSLoc (getTermRep5 _1) <> (loc_2)) (RCon (loc_2) DC_Cons) (getTermRep5 _1)) (getTermRep4 _3)
    getTermRep4 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[8]] =
            (getTermRep5 _1)
    getTermRep5 :: ParsingTree -> (TermRep)
    getTermRep5 (PTBranch _ [PTLeaf (T_pi loc_1), _2@(PTBranch guard2 _)])
        | [guard2] `elem` [[8]] =
            RApp ((loc_1) <> getSLoc (getTermRep5 _2)) (RCon (loc_1) (DC_LO LO_pi)) (getTermRep5 _2)
    getTermRep5 (PTBranch _ [PTLeaf (T_sigma loc_1), _2@(PTBranch guard2 _)])
        | [guard2] `elem` [[8]] =
            RApp ((loc_1) <> getSLoc (getTermRep5 _2)) (RCon (loc_1) (DC_LO LO_sigma)) (getTermRep5 _2)
    getTermRep5 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_Eq loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[9, 9]] =
            RApp (getSLoc (getTermRep6 _1) <> getSLoc (getTermRep6 _3)) (RApp (getSLoc (getTermRep6 _1) <> (loc_2)) (RCon (loc_2) DC_Eq) (getTermRep6 _1)) (getTermRep6 _3)
    getTermRep5 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[9]] =
            (getTermRep6 _1)
    getTermRep6 :: ParsingTree -> (TermRep)
    getTermRep6 (PTBranch _ [_1@(PTBranch guard1 _), _2@(PTBranch guard2 _)])
        | [guard1, guard2] `elem` [[9, 10]] =
            RApp (getSLoc (getTermRep6 _1) <> getSLoc (getTermRep7 _2)) (getTermRep6 _1) (getTermRep7 _2)
    getTermRep6 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[10]] =
            (getTermRep7 _1)
    getTermRep6 (PTBranch _ [PTLeaf (T_succ loc_1)])
        | otherwise =
            RCon (loc_1) DC_Succ
    getTermRep7 :: ParsingTree -> (TermRep)
    getTermRep7 (PTBranch _ [PTLeaf (T_lparen loc_1), _2@(PTBranch guard2 _), PTLeaf (T_rparen loc_3)])
        | [guard2] `elem` [[3]] =
            RPrn ((loc_1) <> (loc_3)) (getTermRep0 _2)
    getTermRep7 (PTBranch _ [PTLeaf (T_cut loc_1)])
        | otherwise =
            RCon (loc_1) (DC_LO LO_cut)
    getTermRep7 (PTBranch _ [PTLeaf (T_true loc_1)])
        | otherwise =
            RCon (loc_1) (DC_LO LO_true)
    getTermRep7 (PTBranch _ [PTLeaf (T_fail loc_1)])
        | otherwise =
            RCon (loc_1) (DC_LO LO_fail)
    getTermRep7 (PTBranch _ [PTLeaf (T_smallid loc_1 contents_1)])
        | otherwise =
            RCon (loc_1) (DC_Named (contents_1))
    getTermRep7 (PTBranch _ [PTLeaf (T_largeid loc_1 contents_1)])
        | otherwise =
            RVar (loc_1) (contents_1)
    getTermRep7 (PTBranch _ [PTLeaf (T_nat_lit loc_1 contents_1)])
        | otherwise =
            mkNatLit (loc_1) (contents_1)
    getTermRep7 (PTBranch _ [PTLeaf (T_str_lit loc_1 contents_1)])
        | otherwise =
            mkStrLit (loc_1) (contents_1)
    getTermRep7 (PTBranch _ [PTLeaf (T_chr_lit loc_1 contents_1)])
        | otherwise =
            mkChrLit (loc_1) (contents_1)
    getTermRep7 (PTBranch _ [PTLeaf (T_lbracket loc_1), PTLeaf (T_rbracket loc_2)])
        | otherwise =
            RCon ((loc_1) <> (loc_2)) DC_Nil
    getTermRep7 (PTBranch _ [PTLeaf (T_lbracket loc_1), _2@(PTBranch guard2 _), PTLeaf (T_rbracket loc_3)])
        | [guard2] `elem` [[11]] =
            RPrn ((loc_1) <> (loc_3)) (getListBody _2)
    getSequence :: (ParsingTree -> (a)) -> ParsingTree -> ([a])
    getSequence getElem (PTBranch _ [])
        | otherwise =
            []
    getSequence getElem (PTBranch _ [_1@(PTBranch guard1 _), _2@(PTBranch guard2 _)])
        | [guard1, guard2] `elem` [[13, 12]] =
            (getElem _1) : (getSequence getElem _2)
    getEither :: (ParsingTree -> (a)) -> (ParsingTree -> (b)) -> ParsingTree -> (Either a b)
    getEither getLeft getRight (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[2]] =
            Left (getLeft _1)
    getEither getLeft getRight (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[12]] =
            Right (getRight _1)
    getListBody :: ParsingTree -> (TermRep)
    getListBody (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[8]] =
            RApp (getSLoc (getTermRep5 _1)) (RApp (getSLoc (getTermRep5 _1)) (RCon (getSLoc (getTermRep5 _1)) DC_Cons) (getTermRep5 _1)) (RCon (getSLoc (getTermRep5 _1)) DC_Nil)
    getListBody (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_comma loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[8, 11]] =
            RApp (getSLoc (getTermRep5 _1) <> getSLoc (getListBody _3)) (RApp (getSLoc (getTermRep5 _1) <> (loc_2)) (RCon (loc_2) DC_Cons) (getTermRep5 _1)) (getListBody _3)
    toTerminal :: (Token) -> TSym
    toTerminal (T_dot loc) = 1
    toTerminal (T_arrow loc) = 2
    toTerminal (T_lparen loc) = 3
    toTerminal (T_rparen loc) = 4
    toTerminal (T_lbracket loc) = 5
    toTerminal (T_rbracket loc) = 6
    toTerminal (T_quest loc) = 7
    toTerminal (T_if loc) = 8
    toTerminal (T_comma loc) = 9
    toTerminal (T_semicolon loc) = 10
    toTerminal (T_fatarrow loc) = 11
    toTerminal (T_pi loc) = 12
    toTerminal (T_sigma loc) = 13
    toTerminal (T_succ loc) = 14
    toTerminal (T_Eq loc) = 15
    toTerminal (T_cut loc) = 16
    toTerminal (T_true loc) = 17
    toTerminal (T_fail loc) = 18
    toTerminal (T_bslash loc) = 19
    toTerminal (T_cons loc) = 20
    toTerminal (T_kind loc) = 21
    toTerminal (T_type loc) = 22
    toTerminal (T_smallid loc contents) = 23
    toTerminal (T_largeid loc contents) = 24
    toTerminal (T_nat_lit loc contents) = 25
    toTerminal (T_chr_lit loc contents) = 26
    toTerminal (T_str_lit loc contents) = 27
    runLR1 :: LR1Parser -> [Token] -> Either (Maybe (Token)) ParsingTree
    runLR1 (LR1Parser getInitS getActionT getReduceT) = go where
        loop inputs = do
            let cur = if null inputs then 0 else toTerminal (head inputs)
                exception = Y.lift (if null inputs then Left Nothing else Left (Just (head inputs)))
            (stack, trees) <- Y.get
            case YMap.lookup (head stack, cur) getActionT of
                Nothing -> exception
                Just Accept -> return ()
                Just (Shift top') -> do
                    Y.put (top' : stack, PTLeaf (head inputs) : trees)
                    loop (tail inputs)
                Just (Reduce (lhs, rhs)) -> do
                    let n = length rhs
                    case YMap.lookup (stack !! n, lhs) getReduceT of
                        Nothing -> exception
                        Just top' -> do
                            Y.put (top' : drop n stack, PTBranch lhs (reverse (take n trees)) : drop n trees)
                            loop inputs
        go tokens = do
            (_, (_, result)) <- Y.runStateT (loop tokens) ([getInitS], [])
            case result of
                [output] -> return output
    theLR1Parser :: LR1Parser
    theLR1Parser = LR1Parser
        { getInitialS = 0
        , getActionTable = YMap.fromAscList 
            [ ((0, 0), Reduce (12, [])), ((0, 3), Shift 19), ((0, 5), Shift 18), ((0, 7), Shift 22), ((0, 12), Shift 21), ((0, 13), Shift 23), ((0, 14), Shift 26), ((0, 16), Shift 14), ((0, 17), Shift 27), ((0, 18), Shift 15), ((0, 21), Shift 16), ((0, 22), Shift 28), ((0, 23), Shift 24), ((0, 24), Shift 17), ((0, 25), Shift 20), ((0, 26), Shift 13), ((0, 27), Shift 25)
            , ((1, 0), Reduce (12, [])), ((1, 3), Shift 19), ((1, 5), Shift 18), ((1, 12), Shift 21), ((1, 13), Shift 23), ((1, 14), Shift 26), ((1, 16), Shift 14), ((1, 17), Shift 27), ((1, 18), Shift 15), ((1, 21), Shift 16), ((1, 22), Shift 28), ((1, 23), Shift 24), ((1, 24), Shift 17), ((1, 25), Shift 20), ((1, 26), Shift 13), ((1, 27), Shift 25)
            , ((2, 0), Reduce (1, [NS 2]))
            , ((3, 1), Shift 30)
            , ((4, 1), Reduce (3, [NS 4])), ((4, 4), Reduce (3, [NS 4])), ((4, 8), Shift 39), ((4, 10), Shift 40)
            , ((5, 1), Reduce (4, [NS 5])), ((5, 4), Reduce (4, [NS 5])), ((5, 8), Reduce (4, [NS 5])), ((5, 10), Reduce (4, [NS 5]))
            , ((6, 1), Reduce (5, [NS 6])), ((6, 4), Reduce (5, [NS 6])), ((6, 8), Reduce (5, [NS 6])), ((6, 9), Shift 42), ((6, 10), Reduce (5, [NS 6])), ((6, 11), Shift 43)
            , ((7, 1), Reduce (6, [NS 7])), ((7, 4), Reduce (6, [NS 7])), ((7, 8), Reduce (6, [NS 7])), ((7, 9), Reduce (6, [NS 7])), ((7, 10), Reduce (6, [NS 7])), ((7, 11), Reduce (6, [NS 7]))
            , ((8, 1), Reduce (7, [NS 8])), ((8, 4), Reduce (7, [NS 8])), ((8, 8), Reduce (7, [NS 8])), ((8, 9), Reduce (7, [NS 8])), ((8, 10), Reduce (7, [NS 8])), ((8, 11), Reduce (7, [NS 8])), ((8, 20), Shift 44)
            , ((9, 1), Reduce (8, [NS 9])), ((9, 3), Shift 19), ((9, 4), Reduce (8, [NS 9])), ((9, 5), Shift 18), ((9, 6), Reduce (8, [NS 9])), ((9, 8), Reduce (8, [NS 9])), ((9, 9), Reduce (8, [NS 9])), ((9, 10), Reduce (8, [NS 9])), ((9, 11), Reduce (8, [NS 9])), ((9, 15), Shift 48), ((9, 16), Shift 14), ((9, 17), Shift 27), ((9, 18), Shift 15), ((9, 20), Reduce (8, [NS 9])), ((9, 23), Shift 24), ((9, 24), Shift 35), ((9, 25), Shift 20), ((9, 26), Shift 13), ((9, 27), Shift 25)
            , ((10, 1), Reduce (9, [NS 10])), ((10, 3), Reduce (9, [NS 10])), ((10, 4), Reduce (9, [NS 10])), ((10, 5), Reduce (9, [NS 10])), ((10, 6), Reduce (9, [NS 10])), ((10, 8), Reduce (9, [NS 10])), ((10, 9), Reduce (9, [NS 10])), ((10, 10), Reduce (9, [NS 10])), ((10, 11), Reduce (9, [NS 10])), ((10, 15), Reduce (9, [NS 10])), ((10, 16), Reduce (9, [NS 10])), ((10, 17), Reduce (9, [NS 10])), ((10, 18), Reduce (9, [NS 10])), ((10, 20), Reduce (9, [NS 10])), ((10, 23), Reduce (9, [NS 10])), ((10, 24), Reduce (9, [NS 10])), ((10, 25), Reduce (9, [NS 10])), ((10, 26), Reduce (9, [NS 10])), ((10, 27), Reduce (9, [NS 10]))
            , ((11, 0), Reduce (1, [NS 12]))
            , ((12, 0), Accept)
            , ((13, 1), Reduce (10, [TS 26])), ((13, 3), Reduce (10, [TS 26])), ((13, 4), Reduce (10, [TS 26])), ((13, 5), Reduce (10, [TS 26])), ((13, 6), Reduce (10, [TS 26])), ((13, 8), Reduce (10, [TS 26])), ((13, 9), Reduce (10, [TS 26])), ((13, 10), Reduce (10, [TS 26])), ((13, 11), Reduce (10, [TS 26])), ((13, 15), Reduce (10, [TS 26])), ((13, 16), Reduce (10, [TS 26])), ((13, 17), Reduce (10, [TS 26])), ((13, 18), Reduce (10, [TS 26])), ((13, 20), Reduce (10, [TS 26])), ((13, 23), Reduce (10, [TS 26])), ((13, 24), Reduce (10, [TS 26])), ((13, 25), Reduce (10, [TS 26])), ((13, 26), Reduce (10, [TS 26])), ((13, 27), Reduce (10, [TS 26]))
            , ((14, 1), Reduce (10, [TS 16])), ((14, 3), Reduce (10, [TS 16])), ((14, 4), Reduce (10, [TS 16])), ((14, 5), Reduce (10, [TS 16])), ((14, 6), Reduce (10, [TS 16])), ((14, 8), Reduce (10, [TS 16])), ((14, 9), Reduce (10, [TS 16])), ((14, 10), Reduce (10, [TS 16])), ((14, 11), Reduce (10, [TS 16])), ((14, 15), Reduce (10, [TS 16])), ((14, 16), Reduce (10, [TS 16])), ((14, 17), Reduce (10, [TS 16])), ((14, 18), Reduce (10, [TS 16])), ((14, 20), Reduce (10, [TS 16])), ((14, 23), Reduce (10, [TS 16])), ((14, 24), Reduce (10, [TS 16])), ((14, 25), Reduce (10, [TS 16])), ((14, 26), Reduce (10, [TS 16])), ((14, 27), Reduce (10, [TS 16]))
            , ((15, 1), Reduce (10, [TS 18])), ((15, 3), Reduce (10, [TS 18])), ((15, 4), Reduce (10, [TS 18])), ((15, 5), Reduce (10, [TS 18])), ((15, 6), Reduce (10, [TS 18])), ((15, 8), Reduce (10, [TS 18])), ((15, 9), Reduce (10, [TS 18])), ((15, 10), Reduce (10, [TS 18])), ((15, 11), Reduce (10, [TS 18])), ((15, 15), Reduce (10, [TS 18])), ((15, 16), Reduce (10, [TS 18])), ((15, 17), Reduce (10, [TS 18])), ((15, 18), Reduce (10, [TS 18])), ((15, 20), Reduce (10, [TS 18])), ((15, 23), Reduce (10, [TS 18])), ((15, 24), Reduce (10, [TS 18])), ((15, 25), Reduce (10, [TS 18])), ((15, 26), Reduce (10, [TS 18])), ((15, 27), Reduce (10, [TS 18]))
            , ((16, 23), Shift 31)
            , ((17, 1), Reduce (10, [TS 24])), ((17, 3), Reduce (10, [TS 24])), ((17, 4), Reduce (10, [TS 24])), ((17, 5), Reduce (10, [TS 24])), ((17, 8), Reduce (10, [TS 24])), ((17, 9), Reduce (10, [TS 24])), ((17, 10), Reduce (10, [TS 24])), ((17, 11), Reduce (10, [TS 24])), ((17, 15), Reduce (10, [TS 24])), ((17, 16), Reduce (10, [TS 24])), ((17, 17), Reduce (10, [TS 24])), ((17, 18), Reduce (10, [TS 24])), ((17, 19), Shift 41), ((17, 20), Reduce (10, [TS 24])), ((17, 23), Reduce (10, [TS 24])), ((17, 24), Reduce (10, [TS 24])), ((17, 25), Reduce (10, [TS 24])), ((17, 26), Reduce (10, [TS 24])), ((17, 27), Reduce (10, [TS 24]))
            , ((18, 3), Shift 19), ((18, 5), Shift 18), ((18, 6), Shift 36), ((18, 12), Shift 21), ((18, 13), Shift 23), ((18, 14), Shift 26), ((18, 16), Shift 14), ((18, 17), Shift 27), ((18, 18), Shift 15), ((18, 23), Shift 24), ((18, 24), Shift 35), ((18, 25), Shift 20), ((18, 26), Shift 13), ((18, 27), Shift 25)
            , ((19, 3), Shift 19), ((19, 5), Shift 18), ((19, 12), Shift 21), ((19, 13), Shift 23), ((19, 14), Shift 26), ((19, 16), Shift 14), ((19, 17), Shift 27), ((19, 18), Shift 15), ((19, 23), Shift 24), ((19, 24), Shift 17), ((19, 25), Shift 20), ((19, 26), Shift 13), ((19, 27), Shift 25)
            , ((20, 1), Reduce (10, [TS 25])), ((20, 3), Reduce (10, [TS 25])), ((20, 4), Reduce (10, [TS 25])), ((20, 5), Reduce (10, [TS 25])), ((20, 6), Reduce (10, [TS 25])), ((20, 8), Reduce (10, [TS 25])), ((20, 9), Reduce (10, [TS 25])), ((20, 10), Reduce (10, [TS 25])), ((20, 11), Reduce (10, [TS 25])), ((20, 15), Reduce (10, [TS 25])), ((20, 16), Reduce (10, [TS 25])), ((20, 17), Reduce (10, [TS 25])), ((20, 18), Reduce (10, [TS 25])), ((20, 20), Reduce (10, [TS 25])), ((20, 23), Reduce (10, [TS 25])), ((20, 24), Reduce (10, [TS 25])), ((20, 25), Reduce (10, [TS 25])), ((20, 26), Reduce (10, [TS 25])), ((20, 27), Reduce (10, [TS 25]))
            , ((21, 3), Shift 19), ((21, 5), Shift 18), ((21, 12), Shift 21), ((21, 13), Shift 23), ((21, 14), Shift 26), ((21, 16), Shift 14), ((21, 17), Shift 27), ((21, 18), Shift 15), ((21, 23), Shift 24), ((21, 24), Shift 35), ((21, 25), Shift 20), ((21, 26), Shift 13), ((21, 27), Shift 25)
            , ((22, 3), Shift 19), ((22, 5), Shift 18), ((22, 12), Shift 21), ((22, 13), Shift 23), ((22, 14), Shift 26), ((22, 16), Shift 14), ((22, 17), Shift 27), ((22, 18), Shift 15), ((22, 23), Shift 24), ((22, 24), Shift 17), ((22, 25), Shift 20), ((22, 26), Shift 13), ((22, 27), Shift 25)
            , ((23, 3), Shift 19), ((23, 5), Shift 18), ((23, 12), Shift 21), ((23, 13), Shift 23), ((23, 14), Shift 26), ((23, 16), Shift 14), ((23, 17), Shift 27), ((23, 18), Shift 15), ((23, 23), Shift 24), ((23, 24), Shift 35), ((23, 25), Shift 20), ((23, 26), Shift 13), ((23, 27), Shift 25)
            , ((24, 1), Reduce (10, [TS 23])), ((24, 3), Reduce (10, [TS 23])), ((24, 4), Reduce (10, [TS 23])), ((24, 5), Reduce (10, [TS 23])), ((24, 6), Reduce (10, [TS 23])), ((24, 8), Reduce (10, [TS 23])), ((24, 9), Reduce (10, [TS 23])), ((24, 10), Reduce (10, [TS 23])), ((24, 11), Reduce (10, [TS 23])), ((24, 15), Reduce (10, [TS 23])), ((24, 16), Reduce (10, [TS 23])), ((24, 17), Reduce (10, [TS 23])), ((24, 18), Reduce (10, [TS 23])), ((24, 20), Reduce (10, [TS 23])), ((24, 23), Reduce (10, [TS 23])), ((24, 24), Reduce (10, [TS 23])), ((24, 25), Reduce (10, [TS 23])), ((24, 26), Reduce (10, [TS 23])), ((24, 27), Reduce (10, [TS 23]))
            , ((25, 1), Reduce (10, [TS 27])), ((25, 3), Reduce (10, [TS 27])), ((25, 4), Reduce (10, [TS 27])), ((25, 5), Reduce (10, [TS 27])), ((25, 6), Reduce (10, [TS 27])), ((25, 8), Reduce (10, [TS 27])), ((25, 9), Reduce (10, [TS 27])), ((25, 10), Reduce (10, [TS 27])), ((25, 11), Reduce (10, [TS 27])), ((25, 15), Reduce (10, [TS 27])), ((25, 16), Reduce (10, [TS 27])), ((25, 17), Reduce (10, [TS 27])), ((25, 18), Reduce (10, [TS 27])), ((25, 20), Reduce (10, [TS 27])), ((25, 23), Reduce (10, [TS 27])), ((25, 24), Reduce (10, [TS 27])), ((25, 25), Reduce (10, [TS 27])), ((25, 26), Reduce (10, [TS 27])), ((25, 27), Reduce (10, [TS 27]))
            , ((26, 1), Reduce (9, [TS 14])), ((26, 3), Reduce (9, [TS 14])), ((26, 4), Reduce (9, [TS 14])), ((26, 5), Reduce (9, [TS 14])), ((26, 6), Reduce (9, [TS 14])), ((26, 8), Reduce (9, [TS 14])), ((26, 9), Reduce (9, [TS 14])), ((26, 10), Reduce (9, [TS 14])), ((26, 11), Reduce (9, [TS 14])), ((26, 15), Reduce (9, [TS 14])), ((26, 16), Reduce (9, [TS 14])), ((26, 17), Reduce (9, [TS 14])), ((26, 18), Reduce (9, [TS 14])), ((26, 20), Reduce (9, [TS 14])), ((26, 23), Reduce (9, [TS 14])), ((26, 24), Reduce (9, [TS 14])), ((26, 25), Reduce (9, [TS 14])), ((26, 26), Reduce (9, [TS 14])), ((26, 27), Reduce (9, [TS 14]))
            , ((27, 1), Reduce (10, [TS 17])), ((27, 3), Reduce (10, [TS 17])), ((27, 4), Reduce (10, [TS 17])), ((27, 5), Reduce (10, [TS 17])), ((27, 6), Reduce (10, [TS 17])), ((27, 8), Reduce (10, [TS 17])), ((27, 9), Reduce (10, [TS 17])), ((27, 10), Reduce (10, [TS 17])), ((27, 11), Reduce (10, [TS 17])), ((27, 15), Reduce (10, [TS 17])), ((27, 16), Reduce (10, [TS 17])), ((27, 17), Reduce (10, [TS 17])), ((27, 18), Reduce (10, [TS 17])), ((27, 20), Reduce (10, [TS 17])), ((27, 23), Reduce (10, [TS 17])), ((27, 24), Reduce (10, [TS 17])), ((27, 25), Reduce (10, [TS 17])), ((27, 26), Reduce (10, [TS 17])), ((27, 27), Reduce (10, [TS 17]))
            , ((28, 23), Shift 32)
            , ((29, 0), Reduce (12, [NS 13, NS 12]))
            , ((30, 0), Reduce (13, [NS 3, TS 1])), ((30, 3), Reduce (13, [NS 3, TS 1])), ((30, 5), Reduce (13, [NS 3, TS 1])), ((30, 12), Reduce (13, [NS 3, TS 1])), ((30, 13), Reduce (13, [NS 3, TS 1])), ((30, 14), Reduce (13, [NS 3, TS 1])), ((30, 16), Reduce (13, [NS 3, TS 1])), ((30, 17), Reduce (13, [NS 3, TS 1])), ((30, 18), Reduce (13, [NS 3, TS 1])), ((30, 21), Reduce (13, [NS 3, TS 1])), ((30, 22), Reduce (13, [NS 3, TS 1])), ((30, 23), Reduce (13, [NS 3, TS 1])), ((30, 24), Reduce (13, [NS 3, TS 1])), ((30, 25), Reduce (13, [NS 3, TS 1])), ((30, 26), Reduce (13, [NS 3, TS 1])), ((30, 27), Reduce (13, [NS 3, TS 1]))
            , ((31, 3), Shift 51), ((31, 22), Shift 52)
            , ((32, 3), Shift 57), ((32, 23), Shift 58), ((32, 24), Shift 56)
            , ((33, 6), Shift 68)
            , ((34, 6), Reduce (11, [NS 8])), ((34, 9), Shift 59)
            , ((35, 1), Reduce (10, [TS 24])), ((35, 3), Reduce (10, [TS 24])), ((35, 4), Reduce (10, [TS 24])), ((35, 5), Reduce (10, [TS 24])), ((35, 6), Reduce (10, [TS 24])), ((35, 8), Reduce (10, [TS 24])), ((35, 9), Reduce (10, [TS 24])), ((35, 10), Reduce (10, [TS 24])), ((35, 11), Reduce (10, [TS 24])), ((35, 15), Reduce (10, [TS 24])), ((35, 16), Reduce (10, [TS 24])), ((35, 17), Reduce (10, [TS 24])), ((35, 18), Reduce (10, [TS 24])), ((35, 20), Reduce (10, [TS 24])), ((35, 23), Reduce (10, [TS 24])), ((35, 24), Reduce (10, [TS 24])), ((35, 25), Reduce (10, [TS 24])), ((35, 26), Reduce (10, [TS 24])), ((35, 27), Reduce (10, [TS 24]))
            , ((36, 1), Reduce (10, [TS 5, TS 6])), ((36, 3), Reduce (10, [TS 5, TS 6])), ((36, 4), Reduce (10, [TS 5, TS 6])), ((36, 5), Reduce (10, [TS 5, TS 6])), ((36, 6), Reduce (10, [TS 5, TS 6])), ((36, 8), Reduce (10, [TS 5, TS 6])), ((36, 9), Reduce (10, [TS 5, TS 6])), ((36, 10), Reduce (10, [TS 5, TS 6])), ((36, 11), Reduce (10, [TS 5, TS 6])), ((36, 15), Reduce (10, [TS 5, TS 6])), ((36, 16), Reduce (10, [TS 5, TS 6])), ((36, 17), Reduce (10, [TS 5, TS 6])), ((36, 18), Reduce (10, [TS 5, TS 6])), ((36, 20), Reduce (10, [TS 5, TS 6])), ((36, 23), Reduce (10, [TS 5, TS 6])), ((36, 24), Reduce (10, [TS 5, TS 6])), ((36, 25), Reduce (10, [TS 5, TS 6])), ((36, 26), Reduce (10, [TS 5, TS 6])), ((36, 27), Reduce (10, [TS 5, TS 6]))
            , ((37, 1), Shift 60)
            , ((38, 4), Shift 69)
            , ((39, 3), Shift 19), ((39, 5), Shift 18), ((39, 12), Shift 21), ((39, 13), Shift 23), ((39, 14), Shift 26), ((39, 16), Shift 14), ((39, 17), Shift 27), ((39, 18), Shift 15), ((39, 23), Shift 24), ((39, 24), Shift 17), ((39, 25), Shift 20), ((39, 26), Shift 13), ((39, 27), Shift 25)
            , ((40, 3), Shift 19), ((40, 5), Shift 18), ((40, 12), Shift 21), ((40, 13), Shift 23), ((40, 14), Shift 26), ((40, 16), Shift 14), ((40, 17), Shift 27), ((40, 18), Shift 15), ((40, 23), Shift 24), ((40, 24), Shift 35), ((40, 25), Shift 20), ((40, 26), Shift 13), ((40, 27), Shift 25)
            , ((41, 3), Shift 19), ((41, 5), Shift 18), ((41, 12), Shift 21), ((41, 13), Shift 23), ((41, 14), Shift 26), ((41, 16), Shift 14), ((41, 17), Shift 27), ((41, 18), Shift 15), ((41, 23), Shift 24), ((41, 24), Shift 17), ((41, 25), Shift 20), ((41, 26), Shift 13), ((41, 27), Shift 25)
            , ((42, 3), Shift 19), ((42, 5), Shift 18), ((42, 12), Shift 21), ((42, 13), Shift 23), ((42, 14), Shift 26), ((42, 16), Shift 14), ((42, 17), Shift 27), ((42, 18), Shift 15), ((42, 23), Shift 24), ((42, 24), Shift 35), ((42, 25), Shift 20), ((42, 26), Shift 13), ((42, 27), Shift 25)
            , ((43, 3), Shift 19), ((43, 5), Shift 18), ((43, 12), Shift 21), ((43, 13), Shift 23), ((43, 14), Shift 26), ((43, 16), Shift 14), ((43, 17), Shift 27), ((43, 18), Shift 15), ((43, 23), Shift 24), ((43, 24), Shift 35), ((43, 25), Shift 20), ((43, 26), Shift 13), ((43, 27), Shift 25)
            , ((44, 3), Shift 19), ((44, 5), Shift 18), ((44, 12), Shift 21), ((44, 13), Shift 23), ((44, 14), Shift 26), ((44, 16), Shift 14), ((44, 17), Shift 27), ((44, 18), Shift 15), ((44, 23), Shift 24), ((44, 24), Shift 35), ((44, 25), Shift 20), ((44, 26), Shift 13), ((44, 27), Shift 25)
            , ((45, 1), Reduce (8, [TS 12, NS 8])), ((45, 4), Reduce (8, [TS 12, NS 8])), ((45, 6), Reduce (8, [TS 12, NS 8])), ((45, 8), Reduce (8, [TS 12, NS 8])), ((45, 9), Reduce (8, [TS 12, NS 8])), ((45, 10), Reduce (8, [TS 12, NS 8])), ((45, 11), Reduce (8, [TS 12, NS 8])), ((45, 20), Reduce (8, [TS 12, NS 8]))
            , ((46, 1), Reduce (8, [TS 13, NS 8])), ((46, 4), Reduce (8, [TS 13, NS 8])), ((46, 6), Reduce (8, [TS 13, NS 8])), ((46, 8), Reduce (8, [TS 13, NS 8])), ((46, 9), Reduce (8, [TS 13, NS 8])), ((46, 10), Reduce (8, [TS 13, NS 8])), ((46, 11), Reduce (8, [TS 13, NS 8])), ((46, 20), Reduce (8, [TS 13, NS 8]))
            , ((47, 1), Reduce (9, [NS 9, NS 10])), ((47, 3), Reduce (9, [NS 9, NS 10])), ((47, 4), Reduce (9, [NS 9, NS 10])), ((47, 5), Reduce (9, [NS 9, NS 10])), ((47, 6), Reduce (9, [NS 9, NS 10])), ((47, 8), Reduce (9, [NS 9, NS 10])), ((47, 9), Reduce (9, [NS 9, NS 10])), ((47, 10), Reduce (9, [NS 9, NS 10])), ((47, 11), Reduce (9, [NS 9, NS 10])), ((47, 15), Reduce (9, [NS 9, NS 10])), ((47, 16), Reduce (9, [NS 9, NS 10])), ((47, 17), Reduce (9, [NS 9, NS 10])), ((47, 18), Reduce (9, [NS 9, NS 10])), ((47, 20), Reduce (9, [NS 9, NS 10])), ((47, 23), Reduce (9, [NS 9, NS 10])), ((47, 24), Reduce (9, [NS 9, NS 10])), ((47, 25), Reduce (9, [NS 9, NS 10])), ((47, 26), Reduce (9, [NS 9, NS 10])), ((47, 27), Reduce (9, [NS 9, NS 10]))
            , ((48, 3), Shift 19), ((48, 5), Shift 18), ((48, 14), Shift 26), ((48, 16), Shift 14), ((48, 17), Shift 27), ((48, 18), Shift 15), ((48, 23), Shift 24), ((48, 24), Shift 35), ((48, 25), Shift 20), ((48, 26), Shift 13), ((48, 27), Shift 25)
            , ((49, 1), Shift 70)
            , ((50, 1), Reduce (14, [NS 15])), ((50, 2), Shift 73), ((50, 4), Reduce (14, [NS 15]))
            , ((51, 3), Shift 51), ((51, 22), Shift 52)
            , ((52, 1), Reduce (15, [TS 22])), ((52, 2), Reduce (15, [TS 22])), ((52, 4), Reduce (15, [TS 22]))
            , ((53, 1), Shift 71)
            , ((54, 1), Reduce (16, [NS 17])), ((54, 2), Shift 77), ((54, 3), Shift 57), ((54, 4), Reduce (16, [NS 17])), ((54, 23), Shift 58), ((54, 24), Shift 56)
            , ((55, 1), Reduce (17, [NS 18])), ((55, 2), Reduce (17, [NS 18])), ((55, 3), Reduce (17, [NS 18])), ((55, 4), Reduce (17, [NS 18])), ((55, 23), Reduce (17, [NS 18])), ((55, 24), Reduce (17, [NS 18]))
            , ((56, 1), Reduce (18, [TS 24])), ((56, 2), Reduce (18, [TS 24])), ((56, 3), Reduce (18, [TS 24])), ((56, 4), Reduce (18, [TS 24])), ((56, 23), Reduce (18, [TS 24])), ((56, 24), Reduce (18, [TS 24]))
            , ((57, 3), Shift 57), ((57, 23), Shift 58), ((57, 24), Shift 56)
            , ((58, 1), Reduce (18, [TS 23])), ((58, 2), Reduce (18, [TS 23])), ((58, 3), Reduce (18, [TS 23])), ((58, 4), Reduce (18, [TS 23])), ((58, 23), Reduce (18, [TS 23])), ((58, 24), Reduce (18, [TS 23]))
            , ((59, 3), Shift 19), ((59, 5), Shift 18), ((59, 12), Shift 21), ((59, 13), Shift 23), ((59, 14), Shift 26), ((59, 16), Shift 14), ((59, 17), Shift 27), ((59, 18), Shift 15), ((59, 23), Shift 24), ((59, 24), Shift 35), ((59, 25), Shift 20), ((59, 26), Shift 13), ((59, 27), Shift 25)
            , ((60, 0), Reduce (2, [TS 7, NS 3, TS 1]))
            , ((61, 1), Reduce (3, [NS 4, TS 8, NS 3])), ((61, 4), Reduce (3, [NS 4, TS 8, NS 3]))
            , ((62, 1), Reduce (3, [TS 24, TS 19, NS 3])), ((62, 4), Reduce (3, [TS 24, TS 19, NS 3]))
            , ((63, 1), Reduce (4, [NS 4, TS 10, NS 5])), ((63, 4), Reduce (4, [NS 4, TS 10, NS 5])), ((63, 8), Reduce (4, [NS 4, TS 10, NS 5])), ((63, 10), Reduce (4, [NS 4, TS 10, NS 5]))
            , ((64, 1), Reduce (5, [NS 6, TS 11, NS 5])), ((64, 4), Reduce (5, [NS 6, TS 11, NS 5])), ((64, 8), Reduce (5, [NS 6, TS 11, NS 5])), ((64, 10), Reduce (5, [NS 6, TS 11, NS 5]))
            , ((65, 1), Reduce (6, [NS 6, TS 9, NS 7])), ((65, 4), Reduce (6, [NS 6, TS 9, NS 7])), ((65, 8), Reduce (6, [NS 6, TS 9, NS 7])), ((65, 9), Reduce (6, [NS 6, TS 9, NS 7])), ((65, 10), Reduce (6, [NS 6, TS 9, NS 7])), ((65, 11), Reduce (6, [NS 6, TS 9, NS 7]))
            , ((66, 1), Reduce (7, [NS 8, TS 20, NS 7])), ((66, 4), Reduce (7, [NS 8, TS 20, NS 7])), ((66, 8), Reduce (7, [NS 8, TS 20, NS 7])), ((66, 9), Reduce (7, [NS 8, TS 20, NS 7])), ((66, 10), Reduce (7, [NS 8, TS 20, NS 7])), ((66, 11), Reduce (7, [NS 8, TS 20, NS 7]))
            , ((67, 1), Reduce (8, [NS 9, TS 15, NS 9])), ((67, 3), Shift 19), ((67, 4), Reduce (8, [NS 9, TS 15, NS 9])), ((67, 5), Shift 18), ((67, 6), Reduce (8, [NS 9, TS 15, NS 9])), ((67, 8), Reduce (8, [NS 9, TS 15, NS 9])), ((67, 9), Reduce (8, [NS 9, TS 15, NS 9])), ((67, 10), Reduce (8, [NS 9, TS 15, NS 9])), ((67, 11), Reduce (8, [NS 9, TS 15, NS 9])), ((67, 16), Shift 14), ((67, 17), Shift 27), ((67, 18), Shift 15), ((67, 20), Reduce (8, [NS 9, TS 15, NS 9])), ((67, 23), Shift 24), ((67, 24), Shift 35), ((67, 25), Shift 20), ((67, 26), Shift 13), ((67, 27), Shift 25)
            , ((68, 1), Reduce (10, [TS 5, NS 11, TS 6])), ((68, 3), Reduce (10, [TS 5, NS 11, TS 6])), ((68, 4), Reduce (10, [TS 5, NS 11, TS 6])), ((68, 5), Reduce (10, [TS 5, NS 11, TS 6])), ((68, 6), Reduce (10, [TS 5, NS 11, TS 6])), ((68, 8), Reduce (10, [TS 5, NS 11, TS 6])), ((68, 9), Reduce (10, [TS 5, NS 11, TS 6])), ((68, 10), Reduce (10, [TS 5, NS 11, TS 6])), ((68, 11), Reduce (10, [TS 5, NS 11, TS 6])), ((68, 15), Reduce (10, [TS 5, NS 11, TS 6])), ((68, 16), Reduce (10, [TS 5, NS 11, TS 6])), ((68, 17), Reduce (10, [TS 5, NS 11, TS 6])), ((68, 18), Reduce (10, [TS 5, NS 11, TS 6])), ((68, 20), Reduce (10, [TS 5, NS 11, TS 6])), ((68, 23), Reduce (10, [TS 5, NS 11, TS 6])), ((68, 24), Reduce (10, [TS 5, NS 11, TS 6])), ((68, 25), Reduce (10, [TS 5, NS 11, TS 6])), ((68, 26), Reduce (10, [TS 5, NS 11, TS 6])), ((68, 27), Reduce (10, [TS 5, NS 11, TS 6]))
            , ((69, 1), Reduce (10, [TS 3, NS 3, TS 4])), ((69, 3), Reduce (10, [TS 3, NS 3, TS 4])), ((69, 4), Reduce (10, [TS 3, NS 3, TS 4])), ((69, 5), Reduce (10, [TS 3, NS 3, TS 4])), ((69, 6), Reduce (10, [TS 3, NS 3, TS 4])), ((69, 8), Reduce (10, [TS 3, NS 3, TS 4])), ((69, 9), Reduce (10, [TS 3, NS 3, TS 4])), ((69, 10), Reduce (10, [TS 3, NS 3, TS 4])), ((69, 11), Reduce (10, [TS 3, NS 3, TS 4])), ((69, 15), Reduce (10, [TS 3, NS 3, TS 4])), ((69, 16), Reduce (10, [TS 3, NS 3, TS 4])), ((69, 17), Reduce (10, [TS 3, NS 3, TS 4])), ((69, 18), Reduce (10, [TS 3, NS 3, TS 4])), ((69, 20), Reduce (10, [TS 3, NS 3, TS 4])), ((69, 23), Reduce (10, [TS 3, NS 3, TS 4])), ((69, 24), Reduce (10, [TS 3, NS 3, TS 4])), ((69, 25), Reduce (10, [TS 3, NS 3, TS 4])), ((69, 26), Reduce (10, [TS 3, NS 3, TS 4])), ((69, 27), Reduce (10, [TS 3, NS 3, TS 4]))
            , ((70, 0), Reduce (13, [TS 21, TS 23, NS 14, TS 1])), ((70, 3), Reduce (13, [TS 21, TS 23, NS 14, TS 1])), ((70, 5), Reduce (13, [TS 21, TS 23, NS 14, TS 1])), ((70, 12), Reduce (13, [TS 21, TS 23, NS 14, TS 1])), ((70, 13), Reduce (13, [TS 21, TS 23, NS 14, TS 1])), ((70, 14), Reduce (13, [TS 21, TS 23, NS 14, TS 1])), ((70, 16), Reduce (13, [TS 21, TS 23, NS 14, TS 1])), ((70, 17), Reduce (13, [TS 21, TS 23, NS 14, TS 1])), ((70, 18), Reduce (13, [TS 21, TS 23, NS 14, TS 1])), ((70, 21), Reduce (13, [TS 21, TS 23, NS 14, TS 1])), ((70, 22), Reduce (13, [TS 21, TS 23, NS 14, TS 1])), ((70, 23), Reduce (13, [TS 21, TS 23, NS 14, TS 1])), ((70, 24), Reduce (13, [TS 21, TS 23, NS 14, TS 1])), ((70, 25), Reduce (13, [TS 21, TS 23, NS 14, TS 1])), ((70, 26), Reduce (13, [TS 21, TS 23, NS 14, TS 1])), ((70, 27), Reduce (13, [TS 21, TS 23, NS 14, TS 1]))
            , ((71, 0), Reduce (13, [TS 22, TS 23, NS 16, TS 1])), ((71, 3), Reduce (13, [TS 22, TS 23, NS 16, TS 1])), ((71, 5), Reduce (13, [TS 22, TS 23, NS 16, TS 1])), ((71, 12), Reduce (13, [TS 22, TS 23, NS 16, TS 1])), ((71, 13), Reduce (13, [TS 22, TS 23, NS 16, TS 1])), ((71, 14), Reduce (13, [TS 22, TS 23, NS 16, TS 1])), ((71, 16), Reduce (13, [TS 22, TS 23, NS 16, TS 1])), ((71, 17), Reduce (13, [TS 22, TS 23, NS 16, TS 1])), ((71, 18), Reduce (13, [TS 22, TS 23, NS 16, TS 1])), ((71, 21), Reduce (13, [TS 22, TS 23, NS 16, TS 1])), ((71, 22), Reduce (13, [TS 22, TS 23, NS 16, TS 1])), ((71, 23), Reduce (13, [TS 22, TS 23, NS 16, TS 1])), ((71, 24), Reduce (13, [TS 22, TS 23, NS 16, TS 1])), ((71, 25), Reduce (13, [TS 22, TS 23, NS 16, TS 1])), ((71, 26), Reduce (13, [TS 22, TS 23, NS 16, TS 1])), ((71, 27), Reduce (13, [TS 22, TS 23, NS 16, TS 1]))
            , ((72, 4), Shift 79)
            , ((73, 3), Shift 51), ((73, 22), Shift 52)
            , ((74, 6), Reduce (11, [NS 8, TS 9, NS 11]))
            , ((75, 4), Shift 81)
            , ((76, 1), Reduce (17, [NS 17, NS 18])), ((76, 2), Reduce (17, [NS 17, NS 18])), ((76, 3), Reduce (17, [NS 17, NS 18])), ((76, 4), Reduce (17, [NS 17, NS 18])), ((76, 23), Reduce (17, [NS 17, NS 18])), ((76, 24), Reduce (17, [NS 17, NS 18]))
            , ((77, 3), Shift 57), ((77, 23), Shift 58), ((77, 24), Shift 56)
            , ((78, 1), Reduce (14, [NS 15, TS 2, NS 14])), ((78, 4), Reduce (14, [NS 15, TS 2, NS 14]))
            , ((79, 1), Reduce (15, [TS 3, NS 14, TS 4])), ((79, 2), Reduce (15, [TS 3, NS 14, TS 4])), ((79, 4), Reduce (15, [TS 3, NS 14, TS 4]))
            , ((80, 1), Reduce (16, [NS 17, TS 2, NS 16])), ((80, 4), Reduce (16, [NS 17, TS 2, NS 16]))
            , ((81, 1), Reduce (18, [TS 3, NS 16, TS 4])), ((81, 2), Reduce (18, [TS 3, NS 16, TS 4])), ((81, 3), Reduce (18, [TS 3, NS 16, TS 4])), ((81, 4), Reduce (18, [TS 3, NS 16, TS 4])), ((81, 23), Reduce (18, [TS 3, NS 16, TS 4])), ((81, 24), Reduce (18, [TS 3, NS 16, TS 4]))
            ]
        , getReduceTable = YMap.fromAscList 
            [ ((0, 1), 12), ((0, 2), 2), ((0, 3), 3), ((0, 4), 4), ((0, 5), 5), ((0, 6), 6), ((0, 7), 7), ((0, 8), 8), ((0, 9), 9), ((0, 10), 10), ((0, 12), 11), ((0, 13), 1)
            , ((1, 3), 3), ((1, 4), 4), ((1, 5), 5), ((1, 6), 6), ((1, 7), 7), ((1, 8), 8), ((1, 9), 9), ((1, 10), 10), ((1, 12), 29), ((1, 13), 1)
            , ((9, 10), 47)
            , ((18, 8), 34), ((18, 9), 9), ((18, 10), 10), ((18, 11), 33)
            , ((19, 3), 38), ((19, 4), 4), ((19, 5), 5), ((19, 6), 6), ((19, 7), 7), ((19, 8), 8), ((19, 9), 9), ((19, 10), 10)
            , ((21, 8), 45), ((21, 9), 9), ((21, 10), 10)
            , ((22, 3), 37), ((22, 4), 4), ((22, 5), 5), ((22, 6), 6), ((22, 7), 7), ((22, 8), 8), ((22, 9), 9), ((22, 10), 10)
            , ((23, 8), 46), ((23, 9), 9), ((23, 10), 10)
            , ((31, 14), 49), ((31, 15), 50)
            , ((32, 16), 53), ((32, 17), 54), ((32, 18), 55)
            , ((39, 3), 61), ((39, 4), 4), ((39, 5), 5), ((39, 6), 6), ((39, 7), 7), ((39, 8), 8), ((39, 9), 9), ((39, 10), 10)
            , ((40, 5), 63), ((40, 6), 6), ((40, 7), 7), ((40, 8), 8), ((40, 9), 9), ((40, 10), 10)
            , ((41, 3), 62), ((41, 4), 4), ((41, 5), 5), ((41, 6), 6), ((41, 7), 7), ((41, 8), 8), ((41, 9), 9), ((41, 10), 10)
            , ((42, 7), 65), ((42, 8), 8), ((42, 9), 9), ((42, 10), 10)
            , ((43, 5), 64), ((43, 6), 6), ((43, 7), 7), ((43, 8), 8), ((43, 9), 9), ((43, 10), 10)
            , ((44, 7), 66), ((44, 8), 8), ((44, 9), 9), ((44, 10), 10)
            , ((48, 9), 67), ((48, 10), 10)
            , ((51, 14), 72), ((51, 15), 50)
            , ((54, 18), 76)
            , ((57, 16), 75), ((57, 17), 54), ((57, 18), 55)
            , ((59, 8), 34), ((59, 9), 9), ((59, 10), 10), ((59, 11), 74)
            , ((67, 10), 47)
            , ((73, 14), 78), ((73, 15), 50)
            , ((77, 16), 80), ((77, 17), 54), ((77, 18), 55)
            ]
        }
{-
    vertices: 
        [ 0: 
            [ <$\ACCEPT> ::= . <Either Query (Sequence Decl)> `\$'
            , <Decl> ::= . <TermRep0> `dot'
            , <Decl> ::= . `kind' `smallid' <KindRep0> `dot'
            , <Decl> ::= . `type' `smallid' <TypeRep0> `dot'
            , <Query> ::= . `quest' <TermRep0> `dot'
            , <TermRep0> ::= . <TermRep1>
            , <TermRep0> ::= . <TermRep1> `if' <TermRep0>
            , <TermRep0> ::= . `largeid' `bslash' <TermRep0>
            , <TermRep1> ::= . <TermRep1> `semicolon' <TermRep2>
            , <TermRep1> ::= . <TermRep2>
            , <TermRep2> ::= . <TermRep3>
            , <TermRep2> ::= . <TermRep3> `fatarrow' <TermRep2>
            , <TermRep3> ::= . <TermRep3> `comma' <TermRep4>
            , <TermRep3> ::= . <TermRep4>
            , <TermRep4> ::= . <TermRep5>
            , <TermRep4> ::= . <TermRep5> `cons' <TermRep4>
            , <TermRep5> ::= . <TermRep6>
            , <TermRep5> ::= . <TermRep6> `eq' <TermRep6>
            , <TermRep5> ::= . `pi' <TermRep5>
            , <TermRep5> ::= . `sigma' <TermRep5>
            , <TermRep6> ::= . <TermRep6> <TermRep7>
            , <TermRep6> ::= . <TermRep7>
            , <TermRep6> ::= . `succ'
            , <TermRep7> ::= . `chrlit'
            , <TermRep7> ::= . `cut'
            , <TermRep7> ::= . `fail'
            , <TermRep7> ::= . `largeid'
            , <TermRep7> ::= . `lbracket' <ListBody> `rbracket'
            , <TermRep7> ::= . `lbracket' `rbracket'
            , <TermRep7> ::= . `lparen' <TermRep0> `rparen'
            , <TermRep7> ::= . `natlit'
            , <TermRep7> ::= . `smallid'
            , <TermRep7> ::= . `strlit'
            , <TermRep7> ::= . `true'
            , <Sequence Decl> ::= .
            , <Sequence Decl> ::= . <Decl> <Sequence Decl>
            , <Either Query (Sequence Decl)> ::= . <Query>
            , <Either Query (Sequence Decl)> ::= . <Sequence Decl>
            ]
        , 12: 
            [ <$\ACCEPT> ::= <Either Query (Sequence Decl)> . `\$'
            ]
        , 1: 
            [ <Decl> ::= . <TermRep0> `dot'
            , <Decl> ::= . `kind' `smallid' <KindRep0> `dot'
            , <Decl> ::= . `type' `smallid' <TypeRep0> `dot'
            , <TermRep0> ::= . <TermRep1>
            , <TermRep0> ::= . <TermRep1> `if' <TermRep0>
            , <TermRep0> ::= . `largeid' `bslash' <TermRep0>
            , <TermRep1> ::= . <TermRep1> `semicolon' <TermRep2>
            , <TermRep1> ::= . <TermRep2>
            , <TermRep2> ::= . <TermRep3>
            , <TermRep2> ::= . <TermRep3> `fatarrow' <TermRep2>
            , <TermRep3> ::= . <TermRep3> `comma' <TermRep4>
            , <TermRep3> ::= . <TermRep4>
            , <TermRep4> ::= . <TermRep5>
            , <TermRep4> ::= . <TermRep5> `cons' <TermRep4>
            , <TermRep5> ::= . <TermRep6>
            , <TermRep5> ::= . <TermRep6> `eq' <TermRep6>
            , <TermRep5> ::= . `pi' <TermRep5>
            , <TermRep5> ::= . `sigma' <TermRep5>
            , <TermRep6> ::= . <TermRep6> <TermRep7>
            , <TermRep6> ::= . <TermRep7>
            , <TermRep6> ::= . `succ'
            , <TermRep7> ::= . `chrlit'
            , <TermRep7> ::= . `cut'
            , <TermRep7> ::= . `fail'
            , <TermRep7> ::= . `largeid'
            , <TermRep7> ::= . `lbracket' <ListBody> `rbracket'
            , <TermRep7> ::= . `lbracket' `rbracket'
            , <TermRep7> ::= . `lparen' <TermRep0> `rparen'
            , <TermRep7> ::= . `natlit'
            , <TermRep7> ::= . `smallid'
            , <TermRep7> ::= . `strlit'
            , <TermRep7> ::= . `true'
            , <Sequence Decl> ::= .
            , <Sequence Decl> ::= . <Decl> <Sequence Decl>
            , <Sequence Decl> ::= <Decl> . <Sequence Decl>
            ]
        , 3: 
            [ <Decl> ::= <TermRep0> . `dot'
            ]
        , 30: 
            [ <Decl> ::= <TermRep0> `dot' .
            ]
        , 16: 
            [ <Decl> ::= `kind' . `smallid' <KindRep0> `dot'
            ]
        , 31: 
            [ <Decl> ::= `kind' `smallid' . <KindRep0> `dot'
            , <KindRep0> ::= . <KindRep1>
            , <KindRep0> ::= . <KindRep1> `arrow' <KindRep0>
            , <KindRep1> ::= . `lparen' <KindRep0> `rparen'
            , <KindRep1> ::= . `type'
            ]
        , 49: 
            [ <Decl> ::= `kind' `smallid' <KindRep0> . `dot'
            ]
        , 70: 
            [ <Decl> ::= `kind' `smallid' <KindRep0> `dot' .
            ]
        , 28: 
            [ <Decl> ::= `type' . `smallid' <TypeRep0> `dot'
            ]
        , 32: 
            [ <Decl> ::= `type' `smallid' . <TypeRep0> `dot'
            , <TypeRep0> ::= . <TypeRep1>
            , <TypeRep0> ::= . <TypeRep1> `arrow' <TypeRep0>
            , <TypeRep1> ::= . <TypeRep1> <TypeRep2>
            , <TypeRep1> ::= . <TypeRep2>
            , <TypeRep2> ::= . `largeid'
            , <TypeRep2> ::= . `lparen' <TypeRep0> `rparen'
            , <TypeRep2> ::= . `smallid'
            ]
        , 53: 
            [ <Decl> ::= `type' `smallid' <TypeRep0> . `dot'
            ]
        , 71: 
            [ <Decl> ::= `type' `smallid' <TypeRep0> `dot' .
            ]
        , 73: 
            [ <KindRep0> ::= . <KindRep1>
            , <KindRep0> ::= . <KindRep1> `arrow' <KindRep0>
            , <KindRep0> ::= <KindRep1> `arrow' . <KindRep0>
            , <KindRep1> ::= . `lparen' <KindRep0> `rparen'
            , <KindRep1> ::= . `type'
            ]
        , 51: 
            [ <KindRep0> ::= . <KindRep1>
            , <KindRep0> ::= . <KindRep1> `arrow' <KindRep0>
            , <KindRep1> ::= . `lparen' <KindRep0> `rparen'
            , <KindRep1> ::= . `type'
            , <KindRep1> ::= `lparen' . <KindRep0> `rparen'
            ]
        , 50: 
            [ <KindRep0> ::= <KindRep1> .
            , <KindRep0> ::= <KindRep1> . `arrow' <KindRep0>
            ]
        , 78: 
            [ <KindRep0> ::= <KindRep1> `arrow' <KindRep0> .
            ]
        , 72: 
            [ <KindRep1> ::= `lparen' <KindRep0> . `rparen'
            ]
        , 79: 
            [ <KindRep1> ::= `lparen' <KindRep0> `rparen' .
            ]
        , 52: 
            [ <KindRep1> ::= `type' .
            ]
        , 59: 
            [ <ListBody> ::= . <TermRep5>
            , <ListBody> ::= . <TermRep5> `comma' <ListBody>
            , <ListBody> ::= <TermRep5> `comma' . <ListBody>
            , <TermRep5> ::= . <TermRep6>
            , <TermRep5> ::= . <TermRep6> `eq' <TermRep6>
            , <TermRep5> ::= . `pi' <TermRep5>
            , <TermRep5> ::= . `sigma' <TermRep5>
            , <TermRep6> ::= . <TermRep6> <TermRep7>
            , <TermRep6> ::= . <TermRep7>
            , <TermRep6> ::= . `succ'
            , <TermRep7> ::= . `chrlit'
            , <TermRep7> ::= . `cut'
            , <TermRep7> ::= . `fail'
            , <TermRep7> ::= . `largeid'
            , <TermRep7> ::= . `lbracket' <ListBody> `rbracket'
            , <TermRep7> ::= . `lbracket' `rbracket'
            , <TermRep7> ::= . `lparen' <TermRep0> `rparen'
            , <TermRep7> ::= . `natlit'
            , <TermRep7> ::= . `smallid'
            , <TermRep7> ::= . `strlit'
            , <TermRep7> ::= . `true'
            ]
        , 18: 
            [ <ListBody> ::= . <TermRep5>
            , <ListBody> ::= . <TermRep5> `comma' <ListBody>
            , <TermRep5> ::= . <TermRep6>
            , <TermRep5> ::= . <TermRep6> `eq' <TermRep6>
            , <TermRep5> ::= . `pi' <TermRep5>
            , <TermRep5> ::= . `sigma' <TermRep5>
            , <TermRep6> ::= . <TermRep6> <TermRep7>
            , <TermRep6> ::= . <TermRep7>
            , <TermRep6> ::= . `succ'
            , <TermRep7> ::= . `chrlit'
            , <TermRep7> ::= . `cut'
            , <TermRep7> ::= . `fail'
            , <TermRep7> ::= . `largeid'
            , <TermRep7> ::= . `lbracket' <ListBody> `rbracket'
            , <TermRep7> ::= . `lbracket' `rbracket'
            , <TermRep7> ::= . `lparen' <TermRep0> `rparen'
            , <TermRep7> ::= . `natlit'
            , <TermRep7> ::= . `smallid'
            , <TermRep7> ::= . `strlit'
            , <TermRep7> ::= . `true'
            , <TermRep7> ::= `lbracket' . <ListBody> `rbracket'
            , <TermRep7> ::= `lbracket' . `rbracket'
            ]
        , 34: 
            [ <ListBody> ::= <TermRep5> .
            , <ListBody> ::= <TermRep5> . `comma' <ListBody>
            ]
        , 74: 
            [ <ListBody> ::= <TermRep5> `comma' <ListBody> .
            ]
        , 22: 
            [ <Query> ::= `quest' . <TermRep0> `dot'
            , <TermRep0> ::= . <TermRep1>
            , <TermRep0> ::= . <TermRep1> `if' <TermRep0>
            , <TermRep0> ::= . `largeid' `bslash' <TermRep0>
            , <TermRep1> ::= . <TermRep1> `semicolon' <TermRep2>
            , <TermRep1> ::= . <TermRep2>
            , <TermRep2> ::= . <TermRep3>
            , <TermRep2> ::= . <TermRep3> `fatarrow' <TermRep2>
            , <TermRep3> ::= . <TermRep3> `comma' <TermRep4>
            , <TermRep3> ::= . <TermRep4>
            , <TermRep4> ::= . <TermRep5>
            , <TermRep4> ::= . <TermRep5> `cons' <TermRep4>
            , <TermRep5> ::= . <TermRep6>
            , <TermRep5> ::= . <TermRep6> `eq' <TermRep6>
            , <TermRep5> ::= . `pi' <TermRep5>
            , <TermRep5> ::= . `sigma' <TermRep5>
            , <TermRep6> ::= . <TermRep6> <TermRep7>
            , <TermRep6> ::= . <TermRep7>
            , <TermRep6> ::= . `succ'
            , <TermRep7> ::= . `chrlit'
            , <TermRep7> ::= . `cut'
            , <TermRep7> ::= . `fail'
            , <TermRep7> ::= . `largeid'
            , <TermRep7> ::= . `lbracket' <ListBody> `rbracket'
            , <TermRep7> ::= . `lbracket' `rbracket'
            , <TermRep7> ::= . `lparen' <TermRep0> `rparen'
            , <TermRep7> ::= . `natlit'
            , <TermRep7> ::= . `smallid'
            , <TermRep7> ::= . `strlit'
            , <TermRep7> ::= . `true'
            ]
        , 37: 
            [ <Query> ::= `quest' <TermRep0> . `dot'
            ]
        , 60: 
            [ <Query> ::= `quest' <TermRep0> `dot' .
            ]
        , 39: 
            [ <TermRep0> ::= . <TermRep1>
            , <TermRep0> ::= . <TermRep1> `if' <TermRep0>
            , <TermRep0> ::= . `largeid' `bslash' <TermRep0>
            , <TermRep0> ::= <TermRep1> `if' . <TermRep0>
            , <TermRep1> ::= . <TermRep1> `semicolon' <TermRep2>
            , <TermRep1> ::= . <TermRep2>
            , <TermRep2> ::= . <TermRep3>
            , <TermRep2> ::= . <TermRep3> `fatarrow' <TermRep2>
            , <TermRep3> ::= . <TermRep3> `comma' <TermRep4>
            , <TermRep3> ::= . <TermRep4>
            , <TermRep4> ::= . <TermRep5>
            , <TermRep4> ::= . <TermRep5> `cons' <TermRep4>
            , <TermRep5> ::= . <TermRep6>
            , <TermRep5> ::= . <TermRep6> `eq' <TermRep6>
            , <TermRep5> ::= . `pi' <TermRep5>
            , <TermRep5> ::= . `sigma' <TermRep5>
            , <TermRep6> ::= . <TermRep6> <TermRep7>
            , <TermRep6> ::= . <TermRep7>
            , <TermRep6> ::= . `succ'
            , <TermRep7> ::= . `chrlit'
            , <TermRep7> ::= . `cut'
            , <TermRep7> ::= . `fail'
            , <TermRep7> ::= . `largeid'
            , <TermRep7> ::= . `lbracket' <ListBody> `rbracket'
            , <TermRep7> ::= . `lbracket' `rbracket'
            , <TermRep7> ::= . `lparen' <TermRep0> `rparen'
            , <TermRep7> ::= . `natlit'
            , <TermRep7> ::= . `smallid'
            , <TermRep7> ::= . `strlit'
            , <TermRep7> ::= . `true'
            ]
        , 41: 
            [ <TermRep0> ::= . <TermRep1>
            , <TermRep0> ::= . <TermRep1> `if' <TermRep0>
            , <TermRep0> ::= . `largeid' `bslash' <TermRep0>
            , <TermRep0> ::= `largeid' `bslash' . <TermRep0>
            , <TermRep1> ::= . <TermRep1> `semicolon' <TermRep2>
            , <TermRep1> ::= . <TermRep2>
            , <TermRep2> ::= . <TermRep3>
            , <TermRep2> ::= . <TermRep3> `fatarrow' <TermRep2>
            , <TermRep3> ::= . <TermRep3> `comma' <TermRep4>
            , <TermRep3> ::= . <TermRep4>
            , <TermRep4> ::= . <TermRep5>
            , <TermRep4> ::= . <TermRep5> `cons' <TermRep4>
            , <TermRep5> ::= . <TermRep6>
            , <TermRep5> ::= . <TermRep6> `eq' <TermRep6>
            , <TermRep5> ::= . `pi' <TermRep5>
            , <TermRep5> ::= . `sigma' <TermRep5>
            , <TermRep6> ::= . <TermRep6> <TermRep7>
            , <TermRep6> ::= . <TermRep7>
            , <TermRep6> ::= . `succ'
            , <TermRep7> ::= . `chrlit'
            , <TermRep7> ::= . `cut'
            , <TermRep7> ::= . `fail'
            , <TermRep7> ::= . `largeid'
            , <TermRep7> ::= . `lbracket' <ListBody> `rbracket'
            , <TermRep7> ::= . `lbracket' `rbracket'
            , <TermRep7> ::= . `lparen' <TermRep0> `rparen'
            , <TermRep7> ::= . `natlit'
            , <TermRep7> ::= . `smallid'
            , <TermRep7> ::= . `strlit'
            , <TermRep7> ::= . `true'
            ]
        , 19: 
            [ <TermRep0> ::= . <TermRep1>
            , <TermRep0> ::= . <TermRep1> `if' <TermRep0>
            , <TermRep0> ::= . `largeid' `bslash' <TermRep0>
            , <TermRep1> ::= . <TermRep1> `semicolon' <TermRep2>
            , <TermRep1> ::= . <TermRep2>
            , <TermRep2> ::= . <TermRep3>
            , <TermRep2> ::= . <TermRep3> `fatarrow' <TermRep2>
            , <TermRep3> ::= . <TermRep3> `comma' <TermRep4>
            , <TermRep3> ::= . <TermRep4>
            , <TermRep4> ::= . <TermRep5>
            , <TermRep4> ::= . <TermRep5> `cons' <TermRep4>
            , <TermRep5> ::= . <TermRep6>
            , <TermRep5> ::= . <TermRep6> `eq' <TermRep6>
            , <TermRep5> ::= . `pi' <TermRep5>
            , <TermRep5> ::= . `sigma' <TermRep5>
            , <TermRep6> ::= . <TermRep6> <TermRep7>
            , <TermRep6> ::= . <TermRep7>
            , <TermRep6> ::= . `succ'
            , <TermRep7> ::= . `chrlit'
            , <TermRep7> ::= . `cut'
            , <TermRep7> ::= . `fail'
            , <TermRep7> ::= . `largeid'
            , <TermRep7> ::= . `lbracket' <ListBody> `rbracket'
            , <TermRep7> ::= . `lbracket' `rbracket'
            , <TermRep7> ::= . `lparen' <TermRep0> `rparen'
            , <TermRep7> ::= . `natlit'
            , <TermRep7> ::= . `smallid'
            , <TermRep7> ::= . `strlit'
            , <TermRep7> ::= . `true'
            , <TermRep7> ::= `lparen' . <TermRep0> `rparen'
            ]
        , 4: 
            [ <TermRep0> ::= <TermRep1> .
            , <TermRep0> ::= <TermRep1> . `if' <TermRep0>
            , <TermRep1> ::= <TermRep1> . `semicolon' <TermRep2>
            ]
        , 61: 
            [ <TermRep0> ::= <TermRep1> `if' <TermRep0> .
            ]
        , 17: 
            [ <TermRep0> ::= `largeid' . `bslash' <TermRep0>
            , <TermRep7> ::= `largeid' .
            ]
        , 62: 
            [ <TermRep0> ::= `largeid' `bslash' <TermRep0> .
            ]
        , 40: 
            [ <TermRep1> ::= <TermRep1> `semicolon' . <TermRep2>
            , <TermRep2> ::= . <TermRep3>
            , <TermRep2> ::= . <TermRep3> `fatarrow' <TermRep2>
            , <TermRep3> ::= . <TermRep3> `comma' <TermRep4>
            , <TermRep3> ::= . <TermRep4>
            , <TermRep4> ::= . <TermRep5>
            , <TermRep4> ::= . <TermRep5> `cons' <TermRep4>
            , <TermRep5> ::= . <TermRep6>
            , <TermRep5> ::= . <TermRep6> `eq' <TermRep6>
            , <TermRep5> ::= . `pi' <TermRep5>
            , <TermRep5> ::= . `sigma' <TermRep5>
            , <TermRep6> ::= . <TermRep6> <TermRep7>
            , <TermRep6> ::= . <TermRep7>
            , <TermRep6> ::= . `succ'
            , <TermRep7> ::= . `chrlit'
            , <TermRep7> ::= . `cut'
            , <TermRep7> ::= . `fail'
            , <TermRep7> ::= . `largeid'
            , <TermRep7> ::= . `lbracket' <ListBody> `rbracket'
            , <TermRep7> ::= . `lbracket' `rbracket'
            , <TermRep7> ::= . `lparen' <TermRep0> `rparen'
            , <TermRep7> ::= . `natlit'
            , <TermRep7> ::= . `smallid'
            , <TermRep7> ::= . `strlit'
            , <TermRep7> ::= . `true'
            ]
        , 63: 
            [ <TermRep1> ::= <TermRep1> `semicolon' <TermRep2> .
            ]
        , 5: 
            [ <TermRep1> ::= <TermRep2> .
            ]
        , 43: 
            [ <TermRep2> ::= . <TermRep3>
            , <TermRep2> ::= . <TermRep3> `fatarrow' <TermRep2>
            , <TermRep2> ::= <TermRep3> `fatarrow' . <TermRep2>
            , <TermRep3> ::= . <TermRep3> `comma' <TermRep4>
            , <TermRep3> ::= . <TermRep4>
            , <TermRep4> ::= . <TermRep5>
            , <TermRep4> ::= . <TermRep5> `cons' <TermRep4>
            , <TermRep5> ::= . <TermRep6>
            , <TermRep5> ::= . <TermRep6> `eq' <TermRep6>
            , <TermRep5> ::= . `pi' <TermRep5>
            , <TermRep5> ::= . `sigma' <TermRep5>
            , <TermRep6> ::= . <TermRep6> <TermRep7>
            , <TermRep6> ::= . <TermRep7>
            , <TermRep6> ::= . `succ'
            , <TermRep7> ::= . `chrlit'
            , <TermRep7> ::= . `cut'
            , <TermRep7> ::= . `fail'
            , <TermRep7> ::= . `largeid'
            , <TermRep7> ::= . `lbracket' <ListBody> `rbracket'
            , <TermRep7> ::= . `lbracket' `rbracket'
            , <TermRep7> ::= . `lparen' <TermRep0> `rparen'
            , <TermRep7> ::= . `natlit'
            , <TermRep7> ::= . `smallid'
            , <TermRep7> ::= . `strlit'
            , <TermRep7> ::= . `true'
            ]
        , 6: 
            [ <TermRep2> ::= <TermRep3> .
            , <TermRep2> ::= <TermRep3> . `fatarrow' <TermRep2>
            , <TermRep3> ::= <TermRep3> . `comma' <TermRep4>
            ]
        , 64: 
            [ <TermRep2> ::= <TermRep3> `fatarrow' <TermRep2> .
            ]
        , 42: 
            [ <TermRep3> ::= <TermRep3> `comma' . <TermRep4>
            , <TermRep4> ::= . <TermRep5>
            , <TermRep4> ::= . <TermRep5> `cons' <TermRep4>
            , <TermRep5> ::= . <TermRep6>
            , <TermRep5> ::= . <TermRep6> `eq' <TermRep6>
            , <TermRep5> ::= . `pi' <TermRep5>
            , <TermRep5> ::= . `sigma' <TermRep5>
            , <TermRep6> ::= . <TermRep6> <TermRep7>
            , <TermRep6> ::= . <TermRep7>
            , <TermRep6> ::= . `succ'
            , <TermRep7> ::= . `chrlit'
            , <TermRep7> ::= . `cut'
            , <TermRep7> ::= . `fail'
            , <TermRep7> ::= . `largeid'
            , <TermRep7> ::= . `lbracket' <ListBody> `rbracket'
            , <TermRep7> ::= . `lbracket' `rbracket'
            , <TermRep7> ::= . `lparen' <TermRep0> `rparen'
            , <TermRep7> ::= . `natlit'
            , <TermRep7> ::= . `smallid'
            , <TermRep7> ::= . `strlit'
            , <TermRep7> ::= . `true'
            ]
        , 65: 
            [ <TermRep3> ::= <TermRep3> `comma' <TermRep4> .
            ]
        , 7: 
            [ <TermRep3> ::= <TermRep4> .
            ]
        , 44: 
            [ <TermRep4> ::= . <TermRep5>
            , <TermRep4> ::= . <TermRep5> `cons' <TermRep4>
            , <TermRep4> ::= <TermRep5> `cons' . <TermRep4>
            , <TermRep5> ::= . <TermRep6>
            , <TermRep5> ::= . <TermRep6> `eq' <TermRep6>
            , <TermRep5> ::= . `pi' <TermRep5>
            , <TermRep5> ::= . `sigma' <TermRep5>
            , <TermRep6> ::= . <TermRep6> <TermRep7>
            , <TermRep6> ::= . <TermRep7>
            , <TermRep6> ::= . `succ'
            , <TermRep7> ::= . `chrlit'
            , <TermRep7> ::= . `cut'
            , <TermRep7> ::= . `fail'
            , <TermRep7> ::= . `largeid'
            , <TermRep7> ::= . `lbracket' <ListBody> `rbracket'
            , <TermRep7> ::= . `lbracket' `rbracket'
            , <TermRep7> ::= . `lparen' <TermRep0> `rparen'
            , <TermRep7> ::= . `natlit'
            , <TermRep7> ::= . `smallid'
            , <TermRep7> ::= . `strlit'
            , <TermRep7> ::= . `true'
            ]
        , 8: 
            [ <TermRep4> ::= <TermRep5> .
            , <TermRep4> ::= <TermRep5> . `cons' <TermRep4>
            ]
        , 66: 
            [ <TermRep4> ::= <TermRep5> `cons' <TermRep4> .
            ]
        , 21: 
            [ <TermRep5> ::= . <TermRep6>
            , <TermRep5> ::= . <TermRep6> `eq' <TermRep6>
            , <TermRep5> ::= . `pi' <TermRep5>
            , <TermRep5> ::= . `sigma' <TermRep5>
            , <TermRep5> ::= `pi' . <TermRep5>
            , <TermRep6> ::= . <TermRep6> <TermRep7>
            , <TermRep6> ::= . <TermRep7>
            , <TermRep6> ::= . `succ'
            , <TermRep7> ::= . `chrlit'
            , <TermRep7> ::= . `cut'
            , <TermRep7> ::= . `fail'
            , <TermRep7> ::= . `largeid'
            , <TermRep7> ::= . `lbracket' <ListBody> `rbracket'
            , <TermRep7> ::= . `lbracket' `rbracket'
            , <TermRep7> ::= . `lparen' <TermRep0> `rparen'
            , <TermRep7> ::= . `natlit'
            , <TermRep7> ::= . `smallid'
            , <TermRep7> ::= . `strlit'
            , <TermRep7> ::= . `true'
            ]
        , 23: 
            [ <TermRep5> ::= . <TermRep6>
            , <TermRep5> ::= . <TermRep6> `eq' <TermRep6>
            , <TermRep5> ::= . `pi' <TermRep5>
            , <TermRep5> ::= . `sigma' <TermRep5>
            , <TermRep5> ::= `sigma' . <TermRep5>
            , <TermRep6> ::= . <TermRep6> <TermRep7>
            , <TermRep6> ::= . <TermRep7>
            , <TermRep6> ::= . `succ'
            , <TermRep7> ::= . `chrlit'
            , <TermRep7> ::= . `cut'
            , <TermRep7> ::= . `fail'
            , <TermRep7> ::= . `largeid'
            , <TermRep7> ::= . `lbracket' <ListBody> `rbracket'
            , <TermRep7> ::= . `lbracket' `rbracket'
            , <TermRep7> ::= . `lparen' <TermRep0> `rparen'
            , <TermRep7> ::= . `natlit'
            , <TermRep7> ::= . `smallid'
            , <TermRep7> ::= . `strlit'
            , <TermRep7> ::= . `true'
            ]
        , 9: 
            [ <TermRep5> ::= <TermRep6> .
            , <TermRep5> ::= <TermRep6> . `eq' <TermRep6>
            , <TermRep6> ::= <TermRep6> . <TermRep7>
            , <TermRep7> ::= . `chrlit'
            , <TermRep7> ::= . `cut'
            , <TermRep7> ::= . `fail'
            , <TermRep7> ::= . `largeid'
            , <TermRep7> ::= . `lbracket' <ListBody> `rbracket'
            , <TermRep7> ::= . `lbracket' `rbracket'
            , <TermRep7> ::= . `lparen' <TermRep0> `rparen'
            , <TermRep7> ::= . `natlit'
            , <TermRep7> ::= . `smallid'
            , <TermRep7> ::= . `strlit'
            , <TermRep7> ::= . `true'
            ]
        , 48: 
            [ <TermRep5> ::= <TermRep6> `eq' . <TermRep6>
            , <TermRep6> ::= . <TermRep6> <TermRep7>
            , <TermRep6> ::= . <TermRep7>
            , <TermRep6> ::= . `succ'
            , <TermRep7> ::= . `chrlit'
            , <TermRep7> ::= . `cut'
            , <TermRep7> ::= . `fail'
            , <TermRep7> ::= . `largeid'
            , <TermRep7> ::= . `lbracket' <ListBody> `rbracket'
            , <TermRep7> ::= . `lbracket' `rbracket'
            , <TermRep7> ::= . `lparen' <TermRep0> `rparen'
            , <TermRep7> ::= . `natlit'
            , <TermRep7> ::= . `smallid'
            , <TermRep7> ::= . `strlit'
            , <TermRep7> ::= . `true'
            ]
        , 67: 
            [ <TermRep5> ::= <TermRep6> `eq' <TermRep6> .
            , <TermRep6> ::= <TermRep6> . <TermRep7>
            , <TermRep7> ::= . `chrlit'
            , <TermRep7> ::= . `cut'
            , <TermRep7> ::= . `fail'
            , <TermRep7> ::= . `largeid'
            , <TermRep7> ::= . `lbracket' <ListBody> `rbracket'
            , <TermRep7> ::= . `lbracket' `rbracket'
            , <TermRep7> ::= . `lparen' <TermRep0> `rparen'
            , <TermRep7> ::= . `natlit'
            , <TermRep7> ::= . `smallid'
            , <TermRep7> ::= . `strlit'
            , <TermRep7> ::= . `true'
            ]
        , 45: 
            [ <TermRep5> ::= `pi' <TermRep5> .
            ]
        , 46: 
            [ <TermRep5> ::= `sigma' <TermRep5> .
            ]
        , 47: 
            [ <TermRep6> ::= <TermRep6> <TermRep7> .
            ]
        , 10: 
            [ <TermRep6> ::= <TermRep7> .
            ]
        , 26: 
            [ <TermRep6> ::= `succ' .
            ]
        , 13: 
            [ <TermRep7> ::= `chrlit' .
            ]
        , 14: 
            [ <TermRep7> ::= `cut' .
            ]
        , 15: 
            [ <TermRep7> ::= `fail' .
            ]
        , 35: 
            [ <TermRep7> ::= `largeid' .
            ]
        , 33: 
            [ <TermRep7> ::= `lbracket' <ListBody> . `rbracket'
            ]
        , 68: 
            [ <TermRep7> ::= `lbracket' <ListBody> `rbracket' .
            ]
        , 36: 
            [ <TermRep7> ::= `lbracket' `rbracket' .
            ]
        , 38: 
            [ <TermRep7> ::= `lparen' <TermRep0> . `rparen'
            ]
        , 69: 
            [ <TermRep7> ::= `lparen' <TermRep0> `rparen' .
            ]
        , 20: 
            [ <TermRep7> ::= `natlit' .
            ]
        , 24: 
            [ <TermRep7> ::= `smallid' .
            ]
        , 25: 
            [ <TermRep7> ::= `strlit' .
            ]
        , 27: 
            [ <TermRep7> ::= `true' .
            ]
        , 77: 
            [ <TypeRep0> ::= . <TypeRep1>
            , <TypeRep0> ::= . <TypeRep1> `arrow' <TypeRep0>
            , <TypeRep0> ::= <TypeRep1> `arrow' . <TypeRep0>
            , <TypeRep1> ::= . <TypeRep1> <TypeRep2>
            , <TypeRep1> ::= . <TypeRep2>
            , <TypeRep2> ::= . `largeid'
            , <TypeRep2> ::= . `lparen' <TypeRep0> `rparen'
            , <TypeRep2> ::= . `smallid'
            ]
        , 57: 
            [ <TypeRep0> ::= . <TypeRep1>
            , <TypeRep0> ::= . <TypeRep1> `arrow' <TypeRep0>
            , <TypeRep1> ::= . <TypeRep1> <TypeRep2>
            , <TypeRep1> ::= . <TypeRep2>
            , <TypeRep2> ::= . `largeid'
            , <TypeRep2> ::= . `lparen' <TypeRep0> `rparen'
            , <TypeRep2> ::= . `smallid'
            , <TypeRep2> ::= `lparen' . <TypeRep0> `rparen'
            ]
        , 54: 
            [ <TypeRep0> ::= <TypeRep1> .
            , <TypeRep0> ::= <TypeRep1> . `arrow' <TypeRep0>
            , <TypeRep1> ::= <TypeRep1> . <TypeRep2>
            , <TypeRep2> ::= . `largeid'
            , <TypeRep2> ::= . `lparen' <TypeRep0> `rparen'
            , <TypeRep2> ::= . `smallid'
            ]
        , 80: 
            [ <TypeRep0> ::= <TypeRep1> `arrow' <TypeRep0> .
            ]
        , 76: 
            [ <TypeRep1> ::= <TypeRep1> <TypeRep2> .
            ]
        , 55: 
            [ <TypeRep1> ::= <TypeRep2> .
            ]
        , 56: 
            [ <TypeRep2> ::= `largeid' .
            ]
        , 75: 
            [ <TypeRep2> ::= `lparen' <TypeRep0> . `rparen'
            ]
        , 81: 
            [ <TypeRep2> ::= `lparen' <TypeRep0> `rparen' .
            ]
        , 58: 
            [ <TypeRep2> ::= `smallid' .
            ]
        , 29: 
            [ <Sequence Decl> ::= <Decl> <Sequence Decl> .
            ]
        , 2: 
            [ <Either Query (Sequence Decl)> ::= <Query> .
            ]
        , 11: 
            [ <Either Query (Sequence Decl)> ::= <Sequence Decl> .
            ]
        ]
    root: 0
    edges: 
        [ (0, <Decl>) +-> 1
        , (0, <Query>) +-> 2
        , (0, <TermRep0>) +-> 3
        , (0, <TermRep1>) +-> 4
        , (0, <TermRep2>) +-> 5
        , (0, <TermRep3>) +-> 6
        , (0, <TermRep4>) +-> 7
        , (0, <TermRep5>) +-> 8
        , (0, <TermRep6>) +-> 9
        , (0, <TermRep7>) +-> 10
        , (0, <Sequence Decl>) +-> 11
        , (0, <Either Query (Sequence Decl)>) +-> 12
        , (0, `chrlit') +-> 13
        , (0, `cut') +-> 14
        , (0, `fail') +-> 15
        , (0, `kind') +-> 16
        , (0, `largeid') +-> 17
        , (0, `lbracket') +-> 18
        , (0, `lparen') +-> 19
        , (0, `natlit') +-> 20
        , (0, `pi') +-> 21
        , (0, `quest') +-> 22
        , (0, `sigma') +-> 23
        , (0, `smallid') +-> 24
        , (0, `strlit') +-> 25
        , (0, `succ') +-> 26
        , (0, `true') +-> 27
        , (0, `type') +-> 28
        , (1, <Decl>) +-> 1
        , (1, <TermRep0>) +-> 3
        , (1, <TermRep1>) +-> 4
        , (1, <TermRep2>) +-> 5
        , (1, <TermRep3>) +-> 6
        , (1, <TermRep4>) +-> 7
        , (1, <TermRep5>) +-> 8
        , (1, <TermRep6>) +-> 9
        , (1, <TermRep7>) +-> 10
        , (1, <Sequence Decl>) +-> 29
        , (1, `chrlit') +-> 13
        , (1, `cut') +-> 14
        , (1, `fail') +-> 15
        , (1, `kind') +-> 16
        , (1, `largeid') +-> 17
        , (1, `lbracket') +-> 18
        , (1, `lparen') +-> 19
        , (1, `natlit') +-> 20
        , (1, `pi') +-> 21
        , (1, `sigma') +-> 23
        , (1, `smallid') +-> 24
        , (1, `strlit') +-> 25
        , (1, `succ') +-> 26
        , (1, `true') +-> 27
        , (1, `type') +-> 28
        , (3, `dot') +-> 30
        , (4, `if') +-> 39
        , (4, `semicolon') +-> 40
        , (6, `comma') +-> 42
        , (6, `fatarrow') +-> 43
        , (8, `cons') +-> 44
        , (9, <TermRep7>) +-> 47
        , (9, `chrlit') +-> 13
        , (9, `cut') +-> 14
        , (9, `eq') +-> 48
        , (9, `fail') +-> 15
        , (9, `largeid') +-> 35
        , (9, `lbracket') +-> 18
        , (9, `lparen') +-> 19
        , (9, `natlit') +-> 20
        , (9, `smallid') +-> 24
        , (9, `strlit') +-> 25
        , (9, `true') +-> 27
        , (16, `smallid') +-> 31
        , (17, `bslash') +-> 41
        , (18, <ListBody>) +-> 33
        , (18, <TermRep5>) +-> 34
        , (18, <TermRep6>) +-> 9
        , (18, <TermRep7>) +-> 10
        , (18, `chrlit') +-> 13
        , (18, `cut') +-> 14
        , (18, `fail') +-> 15
        , (18, `largeid') +-> 35
        , (18, `lbracket') +-> 18
        , (18, `lparen') +-> 19
        , (18, `natlit') +-> 20
        , (18, `pi') +-> 21
        , (18, `rbracket') +-> 36
        , (18, `sigma') +-> 23
        , (18, `smallid') +-> 24
        , (18, `strlit') +-> 25
        , (18, `succ') +-> 26
        , (18, `true') +-> 27
        , (19, <TermRep0>) +-> 38
        , (19, <TermRep1>) +-> 4
        , (19, <TermRep2>) +-> 5
        , (19, <TermRep3>) +-> 6
        , (19, <TermRep4>) +-> 7
        , (19, <TermRep5>) +-> 8
        , (19, <TermRep6>) +-> 9
        , (19, <TermRep7>) +-> 10
        , (19, `chrlit') +-> 13
        , (19, `cut') +-> 14
        , (19, `fail') +-> 15
        , (19, `largeid') +-> 17
        , (19, `lbracket') +-> 18
        , (19, `lparen') +-> 19
        , (19, `natlit') +-> 20
        , (19, `pi') +-> 21
        , (19, `sigma') +-> 23
        , (19, `smallid') +-> 24
        , (19, `strlit') +-> 25
        , (19, `succ') +-> 26
        , (19, `true') +-> 27
        , (21, <TermRep5>) +-> 45
        , (21, <TermRep6>) +-> 9
        , (21, <TermRep7>) +-> 10
        , (21, `chrlit') +-> 13
        , (21, `cut') +-> 14
        , (21, `fail') +-> 15
        , (21, `largeid') +-> 35
        , (21, `lbracket') +-> 18
        , (21, `lparen') +-> 19
        , (21, `natlit') +-> 20
        , (21, `pi') +-> 21
        , (21, `sigma') +-> 23
        , (21, `smallid') +-> 24
        , (21, `strlit') +-> 25
        , (21, `succ') +-> 26
        , (21, `true') +-> 27
        , (22, <TermRep0>) +-> 37
        , (22, <TermRep1>) +-> 4
        , (22, <TermRep2>) +-> 5
        , (22, <TermRep3>) +-> 6
        , (22, <TermRep4>) +-> 7
        , (22, <TermRep5>) +-> 8
        , (22, <TermRep6>) +-> 9
        , (22, <TermRep7>) +-> 10
        , (22, `chrlit') +-> 13
        , (22, `cut') +-> 14
        , (22, `fail') +-> 15
        , (22, `largeid') +-> 17
        , (22, `lbracket') +-> 18
        , (22, `lparen') +-> 19
        , (22, `natlit') +-> 20
        , (22, `pi') +-> 21
        , (22, `sigma') +-> 23
        , (22, `smallid') +-> 24
        , (22, `strlit') +-> 25
        , (22, `succ') +-> 26
        , (22, `true') +-> 27
        , (23, <TermRep5>) +-> 46
        , (23, <TermRep6>) +-> 9
        , (23, <TermRep7>) +-> 10
        , (23, `chrlit') +-> 13
        , (23, `cut') +-> 14
        , (23, `fail') +-> 15
        , (23, `largeid') +-> 35
        , (23, `lbracket') +-> 18
        , (23, `lparen') +-> 19
        , (23, `natlit') +-> 20
        , (23, `pi') +-> 21
        , (23, `sigma') +-> 23
        , (23, `smallid') +-> 24
        , (23, `strlit') +-> 25
        , (23, `succ') +-> 26
        , (23, `true') +-> 27
        , (28, `smallid') +-> 32
        , (31, <KindRep0>) +-> 49
        , (31, <KindRep1>) +-> 50
        , (31, `lparen') +-> 51
        , (31, `type') +-> 52
        , (32, <TypeRep0>) +-> 53
        , (32, <TypeRep1>) +-> 54
        , (32, <TypeRep2>) +-> 55
        , (32, `largeid') +-> 56
        , (32, `lparen') +-> 57
        , (32, `smallid') +-> 58
        , (33, `rbracket') +-> 68
        , (34, `comma') +-> 59
        , (37, `dot') +-> 60
        , (38, `rparen') +-> 69
        , (39, <TermRep0>) +-> 61
        , (39, <TermRep1>) +-> 4
        , (39, <TermRep2>) +-> 5
        , (39, <TermRep3>) +-> 6
        , (39, <TermRep4>) +-> 7
        , (39, <TermRep5>) +-> 8
        , (39, <TermRep6>) +-> 9
        , (39, <TermRep7>) +-> 10
        , (39, `chrlit') +-> 13
        , (39, `cut') +-> 14
        , (39, `fail') +-> 15
        , (39, `largeid') +-> 17
        , (39, `lbracket') +-> 18
        , (39, `lparen') +-> 19
        , (39, `natlit') +-> 20
        , (39, `pi') +-> 21
        , (39, `sigma') +-> 23
        , (39, `smallid') +-> 24
        , (39, `strlit') +-> 25
        , (39, `succ') +-> 26
        , (39, `true') +-> 27
        , (40, <TermRep2>) +-> 63
        , (40, <TermRep3>) +-> 6
        , (40, <TermRep4>) +-> 7
        , (40, <TermRep5>) +-> 8
        , (40, <TermRep6>) +-> 9
        , (40, <TermRep7>) +-> 10
        , (40, `chrlit') +-> 13
        , (40, `cut') +-> 14
        , (40, `fail') +-> 15
        , (40, `largeid') +-> 35
        , (40, `lbracket') +-> 18
        , (40, `lparen') +-> 19
        , (40, `natlit') +-> 20
        , (40, `pi') +-> 21
        , (40, `sigma') +-> 23
        , (40, `smallid') +-> 24
        , (40, `strlit') +-> 25
        , (40, `succ') +-> 26
        , (40, `true') +-> 27
        , (41, <TermRep0>) +-> 62
        , (41, <TermRep1>) +-> 4
        , (41, <TermRep2>) +-> 5
        , (41, <TermRep3>) +-> 6
        , (41, <TermRep4>) +-> 7
        , (41, <TermRep5>) +-> 8
        , (41, <TermRep6>) +-> 9
        , (41, <TermRep7>) +-> 10
        , (41, `chrlit') +-> 13
        , (41, `cut') +-> 14
        , (41, `fail') +-> 15
        , (41, `largeid') +-> 17
        , (41, `lbracket') +-> 18
        , (41, `lparen') +-> 19
        , (41, `natlit') +-> 20
        , (41, `pi') +-> 21
        , (41, `sigma') +-> 23
        , (41, `smallid') +-> 24
        , (41, `strlit') +-> 25
        , (41, `succ') +-> 26
        , (41, `true') +-> 27
        , (42, <TermRep4>) +-> 65
        , (42, <TermRep5>) +-> 8
        , (42, <TermRep6>) +-> 9
        , (42, <TermRep7>) +-> 10
        , (42, `chrlit') +-> 13
        , (42, `cut') +-> 14
        , (42, `fail') +-> 15
        , (42, `largeid') +-> 35
        , (42, `lbracket') +-> 18
        , (42, `lparen') +-> 19
        , (42, `natlit') +-> 20
        , (42, `pi') +-> 21
        , (42, `sigma') +-> 23
        , (42, `smallid') +-> 24
        , (42, `strlit') +-> 25
        , (42, `succ') +-> 26
        , (42, `true') +-> 27
        , (43, <TermRep2>) +-> 64
        , (43, <TermRep3>) +-> 6
        , (43, <TermRep4>) +-> 7
        , (43, <TermRep5>) +-> 8
        , (43, <TermRep6>) +-> 9
        , (43, <TermRep7>) +-> 10
        , (43, `chrlit') +-> 13
        , (43, `cut') +-> 14
        , (43, `fail') +-> 15
        , (43, `largeid') +-> 35
        , (43, `lbracket') +-> 18
        , (43, `lparen') +-> 19
        , (43, `natlit') +-> 20
        , (43, `pi') +-> 21
        , (43, `sigma') +-> 23
        , (43, `smallid') +-> 24
        , (43, `strlit') +-> 25
        , (43, `succ') +-> 26
        , (43, `true') +-> 27
        , (44, <TermRep4>) +-> 66
        , (44, <TermRep5>) +-> 8
        , (44, <TermRep6>) +-> 9
        , (44, <TermRep7>) +-> 10
        , (44, `chrlit') +-> 13
        , (44, `cut') +-> 14
        , (44, `fail') +-> 15
        , (44, `largeid') +-> 35
        , (44, `lbracket') +-> 18
        , (44, `lparen') +-> 19
        , (44, `natlit') +-> 20
        , (44, `pi') +-> 21
        , (44, `sigma') +-> 23
        , (44, `smallid') +-> 24
        , (44, `strlit') +-> 25
        , (44, `succ') +-> 26
        , (44, `true') +-> 27
        , (48, <TermRep6>) +-> 67
        , (48, <TermRep7>) +-> 10
        , (48, `chrlit') +-> 13
        , (48, `cut') +-> 14
        , (48, `fail') +-> 15
        , (48, `largeid') +-> 35
        , (48, `lbracket') +-> 18
        , (48, `lparen') +-> 19
        , (48, `natlit') +-> 20
        , (48, `smallid') +-> 24
        , (48, `strlit') +-> 25
        , (48, `succ') +-> 26
        , (48, `true') +-> 27
        , (49, `dot') +-> 70
        , (50, `arrow') +-> 73
        , (51, <KindRep0>) +-> 72
        , (51, <KindRep1>) +-> 50
        , (51, `lparen') +-> 51
        , (51, `type') +-> 52
        , (53, `dot') +-> 71
        , (54, <TypeRep2>) +-> 76
        , (54, `arrow') +-> 77
        , (54, `largeid') +-> 56
        , (54, `lparen') +-> 57
        , (54, `smallid') +-> 58
        , (57, <TypeRep0>) +-> 75
        , (57, <TypeRep1>) +-> 54
        , (57, <TypeRep2>) +-> 55
        , (57, `largeid') +-> 56
        , (57, `lparen') +-> 57
        , (57, `smallid') +-> 58
        , (59, <ListBody>) +-> 74
        , (59, <TermRep5>) +-> 34
        , (59, <TermRep6>) +-> 9
        , (59, <TermRep7>) +-> 10
        , (59, `chrlit') +-> 13
        , (59, `cut') +-> 14
        , (59, `fail') +-> 15
        , (59, `largeid') +-> 35
        , (59, `lbracket') +-> 18
        , (59, `lparen') +-> 19
        , (59, `natlit') +-> 20
        , (59, `pi') +-> 21
        , (59, `sigma') +-> 23
        , (59, `smallid') +-> 24
        , (59, `strlit') +-> 25
        , (59, `succ') +-> 26
        , (59, `true') +-> 27
        , (67, <TermRep7>) +-> 47
        , (67, `chrlit') +-> 13
        , (67, `cut') +-> 14
        , (67, `fail') +-> 15
        , (67, `largeid') +-> 35
        , (67, `lbracket') +-> 18
        , (67, `lparen') +-> 19
        , (67, `natlit') +-> 20
        , (67, `smallid') +-> 24
        , (67, `strlit') +-> 25
        , (67, `true') +-> 27
        , (72, `rparen') +-> 79
        , (73, <KindRep0>) +-> 78
        , (73, <KindRep1>) +-> 50
        , (73, `lparen') +-> 51
        , (73, `type') +-> 52
        , (75, `rparen') +-> 81
        , (77, <TypeRep0>) +-> 80
        , (77, <TypeRep1>) +-> 54
        , (77, <TypeRep2>) +-> 55
        , (77, `largeid') +-> 56
        , (77, `lparen') +-> 57
        , (77, `smallid') +-> 58
        ]
-}

